-- achievement_data.lua
-- AUTO-GENERATED by scripts/generate_achievement_data.py — do not edit by hand.
-- Source: content/achievements.csv
--
-- ACHIEVEMENTS[id] = { apiName, name, description, hidden, category, icon }
-- ACHIEVEMENT_ORDER  = ids in CSV order (the panel's reading order)
-- ACHIEVEMENT_CATEGORIES = category names in first-seen order
--
-- The UNLOCK CONDITION for each id lives in lua/achievement_rules.lua
-- (ACHIEVEMENT_RULES). A roster entry with no rule, or a rule with no
-- roster entry, fails tests/test_lua_achievements.py.

ACHIEVEMENTS = {}

ACHIEVEMENTS.A_FIRST_NIGHT = { apiName = "ACH_FIRST_NIGHT", name = "First Night", description = "Live through the end of Day 1.", category = "Progress", icon = "ach_first_night" }
ACHIEVEMENTS.A_MIDWEEK = { apiName = "ACH_MIDWEEK", name = "Hump Day", description = "Reach Day 4 with somebody still on their feet.", category = "Progress", icon = "ach_midweek" }
ACHIEVEMENTS.A_SURVIVOR = { apiName = "ACH_SURVIVOR", name = "Starve No More", description = "Survive the whole week.", category = "Progress", icon = "ach_survivor" }
ACHIEVEMENTS.A_PRISTINE = { apiName = "ACH_PRISTINE", name = "Not a Scratch", description = "Win with everyone still standing and nobody brought back.", category = "Mastery", icon = "ach_pristine" }
ACHIEVEMENTS.A_HERO = { apiName = "ACH_HERO", name = "Hero Run", description = "Put down all three phase bosses in a single week.", category = "Mastery", icon = "ach_hero" }
ACHIEVEMENTS.A_TRUTH = { apiName = "ACH_TRUTH", name = "The Truth", description = "Collect all three Clues.", category = "Mastery", icon = "ach_truth" }
ACHIEVEMENTS.A_NIGHTMARE = { apiName = "ACH_NIGHTMARE", name = "Nightmare Fuel", description = "Win a game on Nightmare.", category = "Mastery", icon = "ach_nightmare" }
ACHIEVEMENTS.A_WEEKEND = { apiName = "ACH_WEEKEND", name = "Long Weekend", description = "Win a Long Weekend game.", category = "Mastery", icon = "ach_weekend" }
ACHIEVEMENTS.A_SOLO = { apiName = "ACH_SOLO", name = "Alone Together", description = "Win a solo game.", category = "Mastery", icon = "ach_solo" }
ACHIEVEMENTS.A_DEERCLOPS = { apiName = "ACH_DEERCLOPS", name = "Antlers Down", description = "Bring down the Deerclops.", category = "Bosses", icon = "ach_deerclops" }
ACHIEVEMENTS.A_EYE = { apiName = "ACH_EYE", name = "Eye Contact", description = "Destroy the Eye of Terror.", category = "Bosses", icon = "ach_eye" }
ACHIEVEMENTS.A_SOURCE = { apiName = "ACH_SOURCE", name = "Cut the Source", description = "Bring down The Source.", category = "Bosses", icon = "ach_source" }
ACHIEVEMENTS.A_TREEGUARD = { apiName = "ACH_TREEGUARD", name = "Timber", description = "Put down a Treeguard.", category = "Bosses", icon = "ach_treeguard" }
ACHIEVEMENTS.A_CAMP_MOTHER = { apiName = "ACH_CAMP_MOTHER", name = "Camp Mother", description = "Cook ten meals in one week.", category = "Habits", icon = "ach_camp_mother" }
ACHIEVEMENTS.A_HANDY = { apiName = "ACH_HANDY", name = "Handy", description = "Craft eight items in one week.", category = "Habits", icon = "ach_handy" }
ACHIEVEMENTS.A_WATCH = { apiName = "ACH_WATCH", name = "Neighbourhood Watch", description = "Defeat fifteen threats in one week.", category = "Habits", icon = "ach_watch" }
ACHIEVEMENTS.A_PRESS = { apiName = "ACH_PRESS", name = "Press the Attack", description = "Finish three threats by pressing the attack.", category = "Habits", icon = "ach_press" }
ACHIEVEMENTS.A_ALL_HANDS = { apiName = "ACH_ALL_HANDS", name = "All Hands", description = "Every character in play uses their Signature Move.", category = "Habits", icon = "ach_all_hands" }
ACHIEVEMENTS.A_DARE = { apiName = "ACH_DARE", name = "Hold My Energy Drink", description = "Take five dares in one week.", category = "Habits", icon = "ach_dare" }
ACHIEVEMENTS.A_HEART = { apiName = "ACH_HEART", name = "Telltale Heart", description = "Bring a fallen friend back.", category = "Habits", icon = "ach_heart" }
ACHIEVEMENTS.A_WIRE = { apiName = "ACH_WIRE", name = "Down to the Wire", description = "Win with two or less Doom left on the track.", category = "Mastery", icon = "ach_wire" }
ACHIEVEMENTS.A_SPLIT = { apiName = "ACH_SPLIT", name = "It Splits", description = "See The Source come apart.", category = "Secret", icon = "ach_split", hidden = true }
ACHIEVEMENTS.A_CHARLIE = { apiName = "ACH_CHARLIE", name = "Who's There?", description = "Survive three nights running with something in the dark following you.", category = "Secret", icon = "ach_charlie", hidden = true }
ACHIEVEMENTS.A_LAST_ONE = { apiName = "ACH_LAST_ONE", name = "Last One Standing", description = "Win the week with exactly one character still on their feet.", category = "Secret", icon = "ach_last_one", hidden = true }

ACHIEVEMENT_ORDER = {
    "A_FIRST_NIGHT",
    "A_MIDWEEK",
    "A_SURVIVOR",
    "A_PRISTINE",
    "A_HERO",
    "A_TRUTH",
    "A_NIGHTMARE",
    "A_WEEKEND",
    "A_SOLO",
    "A_DEERCLOPS",
    "A_EYE",
    "A_SOURCE",
    "A_TREEGUARD",
    "A_CAMP_MOTHER",
    "A_HANDY",
    "A_WATCH",
    "A_PRESS",
    "A_ALL_HANDS",
    "A_DARE",
    "A_HEART",
    "A_WIRE",
    "A_SPLIT",
    "A_CHARLIE",
    "A_LAST_ONE",
}

ACHIEVEMENT_CATEGORIES = { "Progress", "Mastery", "Bosses", "Habits", "Secret" }
