-- audio_manifest.lua
-- AUTO-GENERATED by scripts/generate_audio_manifest.py — do not edit by hand.
-- Sources: sounds/ambient/suburban, sounds/ambient/varied, sounds/creatures/*, sounds/sfx
-- Durations: precise for .wav; estimated from filesize for .mp3 (avg 128 kbps).

AUDIO = {}

AUDIO.AMBIENT_SUBURBAN = {
    { url = "http://localhost:8080/sounds/ambient/suburban/dontstarve_dlc003_amb_temperate_interior_city_day.wav", duration = 51.26, name = "dontstarve_dlc003_amb_temperate_interior_city_day.wav" },
    { url = "http://localhost:8080/sounds/ambient/suburban/suburbs_fall_day_amb_dsh.wav", duration = 113.53, name = "suburbs_fall_day_amb_dsh.wav" },
}

AUDIO.AMBIENT_VARIED = {
    { url = "http://localhost:8080/sounds/ambient/varied/badland_summer_lp.mp3", duration = 54.88, name = "badland_summer_lp.mp3" },
    { url = "http://localhost:8080/sounds/ambient/varied/battlegrounds fall night_ds_amb.wav", duration = 99.08, name = "battlegrounds fall night_ds_amb.wav" },
    { url = "http://localhost:8080/sounds/ambient/varied/cave_lp.mp3", duration = 80.05, name = "cave_lp.mp3" },
    { url = "http://localhost:8080/sounds/ambient/varied/deep_jungle_fall_night.wav", duration = 112.88, name = "deep_jungle_fall_night.wav" },
    { url = "http://localhost:8080/sounds/ambient/varied/forest_summer_lp.mp3", duration = 75.40, name = "forest_summer_lp.mp3" },
    { url = "http://localhost:8080/sounds/ambient/varied/grasslandry_day_lp.mp3", duration = 47.50, name = "grasslandry_day_lp.mp3" },
    { url = "http://localhost:8080/sounds/ambient/varied/hamlet_amb_cave_st_lp.wav", duration = 116.64, name = "hamlet_amb_cave_st_lp.wav" },
    { url = "http://localhost:8080/sounds/ambient/varied/jungle_wet_night_lp.mp3", duration = 46.43, name = "jungle_wet_night_lp.mp3" },
    { url = "http://localhost:8080/sounds/ambient/varied/mangrove_dry_day.mp3", duration = 46.58, name = "mangrove_dry_day.mp3" },
    { url = "http://localhost:8080/sounds/ambient/varied/mangrove_hurricane_day.mp3", duration = 46.25, name = "mangrove_hurricane_day.mp3" },
    { url = "http://localhost:8080/sounds/ambient/varied/wind_heavy_lp.mp3", duration = 39.37, name = "wind_heavy_lp.mp3" },
    { url = "http://localhost:8080/sounds/ambient/varied/wind_light_lp.mp3", duration = 31.67, name = "wind_light_lp.mp3" },
    { url = "http://localhost:8080/sounds/ambient/varied/winterwind_lp.mp3", duration = 43.09, name = "winterwind_lp.mp3" },
}

AUDIO.AMBIENT_NIGHT = {
    { url = "http://localhost:8080/sounds/ambient/night/night_drone_cold.wav", duration = 72.00, name = "night_drone_cold.wav" },
    { url = "http://localhost:8080/sounds/ambient/night/night_drone_hollow.wav", duration = 72.00, name = "night_drone_hollow.wav" },
    { url = "http://localhost:8080/sounds/ambient/night/night_drone_low.wav", duration = 72.00, name = "night_drone_low.wav" },
}

AUDIO.CREATURES = {}
AUDIO.CREATURES.bearger = {
    { url = "http://localhost:8080/sounds/creatures/bearger/bearger_attack_1.mp3", duration = 0.55, name = "bearger_attack_1.mp3" },
    { url = "http://localhost:8080/sounds/creatures/bearger/bearger_attack_2.mp3", duration = 0.63, name = "bearger_attack_2.mp3" },
    { url = "http://localhost:8080/sounds/creatures/bearger/bearger_chew_1.mp3", duration = 0.33, name = "bearger_chew_1.mp3" },
    { url = "http://localhost:8080/sounds/creatures/bearger/bearger_chew_2.mp3", duration = 0.27, name = "bearger_chew_2.mp3" },
    { url = "http://localhost:8080/sounds/creatures/bearger/bearger_chew_3.mp3", duration = 0.12, name = "bearger_chew_3.mp3" },
    { url = "http://localhost:8080/sounds/creatures/bearger/bearger_death_1.mp3", duration = 0.57, name = "bearger_death_1.mp3" },
    { url = "http://localhost:8080/sounds/creatures/bearger/bearger_distant_1.mp3", duration = 2.78, name = "bearger_distant_1.mp3" },
}

AUDIO.CREATURES.deerclops = {
    { url = "http://localhost:8080/sounds/creatures/deerclops/deerclops_attack_1.mp3", duration = 0.46, name = "deerclops_attack_1.mp3" },
    { url = "http://localhost:8080/sounds/creatures/deerclops/deerclops_attack_2.mp3", duration = 0.38, name = "deerclops_attack_2.mp3" },
    { url = "http://localhost:8080/sounds/creatures/deerclops/deerclops_attack_3.mp3", duration = 0.46, name = "deerclops_attack_3.mp3" },
    { url = "http://localhost:8080/sounds/creatures/deerclops/deerclops_attack_4.mp3", duration = 0.42, name = "deerclops_attack_4.mp3" },
    { url = "http://localhost:8080/sounds/creatures/deerclops/deerclops_attack_5.mp3", duration = 0.46, name = "deerclops_attack_5.mp3" },
    { url = "http://localhost:8080/sounds/creatures/deerclops/deerclops_death_1.mp3", duration = 1.23, name = "deerclops_death_1.mp3" },
    { url = "http://localhost:8080/sounds/creatures/deerclops/deerclops_death_2.mp3", duration = 1.36, name = "deerclops_death_2.mp3" },
    { url = "http://localhost:8080/sounds/creatures/deerclops/deerclops_distant_1.mp3", duration = 4.28, name = "deerclops_distant_1.mp3" },
    { url = "http://localhost:8080/sounds/creatures/deerclops/deerclops_distant_2.mp3", duration = 3.94, name = "deerclops_distant_2.mp3" },
    { url = "http://localhost:8080/sounds/creatures/deerclops/deerclops_distant_3.mp3", duration = 4.61, name = "deerclops_distant_3.mp3" },
    { url = "http://localhost:8080/sounds/creatures/deerclops/deerclops_distant_4.mp3", duration = 3.92, name = "deerclops_distant_4.mp3" },
}

AUDIO.CREATURES.eye_of_terror = {
    { url = "http://localhost:8080/sounds/creatures/eye_of_terror/Tentacle_attack_1.mp3", duration = 0.08, name = "Tentacle_attack_1.mp3" },
    { url = "http://localhost:8080/sounds/creatures/eye_of_terror/Tentacle_attack_2.mp3", duration = 0.10, name = "Tentacle_attack_2.mp3" },
    { url = "http://localhost:8080/sounds/creatures/eye_of_terror/Tentacle_attack_3.mp3", duration = 0.07, name = "Tentacle_attack_3.mp3" },
    { url = "http://localhost:8080/sounds/creatures/eye_of_terror/Tentacle_attack_4.mp3", duration = 0.08, name = "Tentacle_attack_4.mp3" },
    { url = "http://localhost:8080/sounds/creatures/eye_of_terror/Tentacle_attack_5.mp3", duration = 0.10, name = "Tentacle_attack_5.mp3" },
    { url = "http://localhost:8080/sounds/creatures/eye_of_terror/Tentacle_voice_appear_1.mp3", duration = 0.73, name = "Tentacle_voice_appear_1.mp3" },
    { url = "http://localhost:8080/sounds/creatures/eye_of_terror/Tentacle_voice_appear_2.mp3", duration = 0.74, name = "Tentacle_voice_appear_2.mp3" },
    { url = "http://localhost:8080/sounds/creatures/eye_of_terror/Tentacle_voice_appear_3.mp3", duration = 0.74, name = "Tentacle_voice_appear_3.mp3" },
    { url = "http://localhost:8080/sounds/creatures/eye_of_terror/Tentacle_voice_appear_4.mp3", duration = 0.73, name = "Tentacle_voice_appear_4.mp3" },
    { url = "http://localhost:8080/sounds/creatures/eye_of_terror/Tentacle_voice_death_1.mp3", duration = 0.92, name = "Tentacle_voice_death_1.mp3" },
    { url = "http://localhost:8080/sounds/creatures/eye_of_terror/Tentacle_voice_death_2.mp3", duration = 0.92, name = "Tentacle_voice_death_2.mp3" },
    { url = "http://localhost:8080/sounds/creatures/eye_of_terror/Tentacle_voice_death_3.mp3", duration = 0.89, name = "Tentacle_voice_death_3.mp3" },
    { url = "http://localhost:8080/sounds/creatures/eye_of_terror/Tentacle_voice_death_4.mp3", duration = 0.90, name = "Tentacle_voice_death_4.mp3" },
}

AUDIO.CREATURES.treeguard = {
    { url = "http://localhost:8080/sounds/creatures/treeguard/Leif_VO_attack_1.mp3", duration = 0.51, name = "Leif_VO_attack_1.mp3" },
    { url = "http://localhost:8080/sounds/creatures/treeguard/Leif_VO_attack_10.mp3", duration = 0.48, name = "Leif_VO_attack_10.mp3" },
    { url = "http://localhost:8080/sounds/creatures/treeguard/Leif_VO_attack_11.mp3", duration = 0.52, name = "Leif_VO_attack_11.mp3" },
    { url = "http://localhost:8080/sounds/creatures/treeguard/Leif_VO_attack_12.mp3", duration = 0.48, name = "Leif_VO_attack_12.mp3" },
    { url = "http://localhost:8080/sounds/creatures/treeguard/Leif_VO_attack_13.mp3", duration = 0.46, name = "Leif_VO_attack_13.mp3" },
    { url = "http://localhost:8080/sounds/creatures/treeguard/Leif_VO_attack_2.mp3", duration = 0.48, name = "Leif_VO_attack_2.mp3" },
    { url = "http://localhost:8080/sounds/creatures/treeguard/Leif_VO_attack_3.mp3", duration = 0.48, name = "Leif_VO_attack_3.mp3" },
    { url = "http://localhost:8080/sounds/creatures/treeguard/Leif_VO_attack_4.mp3", duration = 0.48, name = "Leif_VO_attack_4.mp3" },
    { url = "http://localhost:8080/sounds/creatures/treeguard/Leif_VO_attack_5.mp3", duration = 0.51, name = "Leif_VO_attack_5.mp3" },
    { url = "http://localhost:8080/sounds/creatures/treeguard/Leif_VO_attack_6.mp3", duration = 0.51, name = "Leif_VO_attack_6.mp3" },
    { url = "http://localhost:8080/sounds/creatures/treeguard/Leif_VO_attack_7.mp3", duration = 0.51, name = "Leif_VO_attack_7.mp3" },
    { url = "http://localhost:8080/sounds/creatures/treeguard/Leif_VO_attack_8.mp3", duration = 0.51, name = "Leif_VO_attack_8.mp3" },
    { url = "http://localhost:8080/sounds/creatures/treeguard/Leif_VO_attack_9.mp3", duration = 0.50, name = "Leif_VO_attack_9.mp3" },
    { url = "http://localhost:8080/sounds/creatures/treeguard/Leif_VO_death_1.mp3", duration = 0.91, name = "Leif_VO_death_1.mp3" },
    { url = "http://localhost:8080/sounds/creatures/treeguard/Leif_VO_death_2.mp3", duration = 0.77, name = "Leif_VO_death_2.mp3" },
    { url = "http://localhost:8080/sounds/creatures/treeguard/Leif_VO_death_3.mp3", duration = 0.77, name = "Leif_VO_death_3.mp3" },
    { url = "http://localhost:8080/sounds/creatures/treeguard/Leif_VO_death_4.mp3", duration = 0.78, name = "Leif_VO_death_4.mp3" },
    { url = "http://localhost:8080/sounds/creatures/treeguard/Leif_branchfoley_1.mp3", duration = 0.47, name = "Leif_branchfoley_1.mp3" },
    { url = "http://localhost:8080/sounds/creatures/treeguard/Leif_branchfoley_10.mp3", duration = 0.48, name = "Leif_branchfoley_10.mp3" },
    { url = "http://localhost:8080/sounds/creatures/treeguard/Leif_branchfoley_3.mp3", duration = 0.55, name = "Leif_branchfoley_3.mp3" },
    { url = "http://localhost:8080/sounds/creatures/treeguard/Leif_branchfoley_4.mp3", duration = 0.56, name = "Leif_branchfoley_4.mp3" },
    { url = "http://localhost:8080/sounds/creatures/treeguard/Leif_branchfoley_5.mp3", duration = 0.80, name = "Leif_branchfoley_5.mp3" },
    { url = "http://localhost:8080/sounds/creatures/treeguard/Leif_branchfoley_6.mp3", duration = 0.48, name = "Leif_branchfoley_6.mp3" },
    { url = "http://localhost:8080/sounds/creatures/treeguard/Leif_branchfoley_7.mp3", duration = 0.59, name = "Leif_branchfoley_7.mp3" },
    { url = "http://localhost:8080/sounds/creatures/treeguard/Leif_branchfoley_8.mp3", duration = 0.51, name = "Leif_branchfoley_8.mp3" },
    { url = "http://localhost:8080/sounds/creatures/treeguard/Leif_branchfoley_9.mp3", duration = 0.55, name = "Leif_branchfoley_9.mp3" },
}

AUDIO.SFX = {}
AUDIO.SFX.character_death = { url = "http://localhost:8080/sounds/sfx/Character_Death_Sound.mp3", duration = 2.17, name = "Character_Death_Sound.mp3" }
AUDIO.SFX.character_meet = { url = "http://localhost:8080/sounds/sfx/Character_Meet_Sound.mp3", duration = 1.68, name = "Character_Meet_Sound.mp3" }
AUDIO.SFX.character_talktrade = { url = "http://localhost:8080/sounds/sfx/Character_TalkTrade_Sound.mp3", duration = 2.59, name = "Character_TalkTrade_Sound.mp3" }
AUDIO.SFX.character_walk = { url = "http://localhost:8080/sounds/sfx/Character_Walk_Sound.mp3", duration = 3.11, name = "Character_Walk_Sound.mp3" }
AUDIO.SFX.night_growl = { url = "http://localhost:8080/sounds/sfx/night_growl.wav", duration = 2.20, name = "night_growl.wav" }
AUDIO.SFX.tick_chime = { url = "http://localhost:8080/sounds/sfx/tick_chime.wav", duration = 1.60, name = "tick_chime.wav" }
AUDIO.SFX.turn_ping = { url = "http://localhost:8080/sounds/sfx/Turn_Ping_Sound.wav", duration = 0.52, name = "Turn_Ping_Sound.wav" }
