-- market_data.lua
-- AUTO-GENERATED by scripts/generate_market_data.py — do not edit by hand.
-- Source: content/cards_market.csv (cost column)
--
-- MARKET_COSTS[card_id] = { ResourceName = qty, ... }
-- Body-cost terms (Health, Sanity) are intentionally omitted —
-- only bag-token resources count for affordability highlighting.

MARKET_COSTS = {}

-- M_FLASHLIGHT (Flashlight): 1 Metal + 1 Battery
MARKET_COSTS.M_FLASHLIGHT = { Battery = 1, Metal = 1 }
-- M_CROWBAR (Crowbar): 2 Metal + 1 Wood
MARKET_COSTS.M_CROWBAR = { Metal = 2, Wood = 1 }
-- M_FIRST_AID (First Aid Kit): 1 Cloth + 1 Metal
MARKET_COSTS.M_FIRST_AID = { Cloth = 1, Metal = 1 }
-- M_BANDAGE (Bandage): 1 Cloth
MARKET_COSTS.M_BANDAGE = { Cloth = 1 }
-- M_BAT (Improvised Bat): 1 Wood + 1 Cloth
MARKET_COSTS.M_BAT = { Cloth = 1, Wood = 1 }
-- M_SHARPENED_SPOON (Sharpened Spoon): 1 Metal
MARKET_COSTS.M_SHARPENED_SPOON = { Metal = 1 }
-- M_SLINGSHOT (Slingshot): 1 Wood + 1 Cloth
MARKET_COSTS.M_SLINGSHOT = { Cloth = 1, Wood = 1 }
-- M_TOY_BOW (Toy Bow): 1 Wood + 2 Cloth
MARKET_COSTS.M_TOY_BOW = { Cloth = 2, Wood = 1 }
-- M_STUFFED_ANIMAL (Stuffed Animal): 1 Cloth + 1 Food
MARKET_COSTS.M_STUFFED_ANIMAL = { Cloth = 1, Food = 1 }
-- M_PHOTO_ALBUM (Photo Album): 2 Cloth
MARKET_COSTS.M_PHOTO_ALBUM = { Cloth = 2 }
-- M_MUSIC_PLAYER (Music Player): 1 Metal + 1 Battery
MARKET_COSTS.M_MUSIC_PLAYER = { Battery = 1, Metal = 1 }
-- M_WARM_BLANKET (Warm Blanket): 2 Cloth
MARKET_COSTS.M_WARM_BLANKET = { Cloth = 2 }
-- M_ENERGY_BAR (Energy Bar): 1 Food
MARKET_COSTS.M_ENERGY_BAR = { Food = 1 }
-- M_HOT_COCOA (Hot Cocoa): 1 Food + 1 Wood
MARKET_COSTS.M_HOT_COCOA = { Food = 1, Wood = 1 }
-- M_BACKPACK (Backpack): 2 Cloth + 1 Metal
MARKET_COSTS.M_BACKPACK = { Cloth = 2, Metal = 1 }
-- M_CIRCLE_OF_SALT (Circle of Salt): 1 Food (salt) + 1 Cloth
MARKET_COSTS.M_CIRCLE_OF_SALT = { Cloth = 1 }
-- M_CLUE_TAPE (Clue: A Cassette): 1 Battery
MARKET_COSTS.M_CLUE_TAPE = { Battery = 1 }
-- M_CLUE_NOTE (Clue: A Burned Note): 1 Cloth
MARKET_COSTS.M_CLUE_NOTE = { Cloth = 1 }
-- M_CLUE_PHOTO (Clue: A Polaroid): 1 Battery
MARKET_COSTS.M_CLUE_PHOTO = { Battery = 1 }
-- M_RADIO (Radio): 1 Metal + 1 Battery + 1 Cloth
MARKET_COSTS.M_RADIO = { Battery = 1, Cloth = 1, Metal = 1 }
-- M_HEADPHONES (Headphones): 1 Metal + 1 Cloth
MARKET_COSTS.M_HEADPHONES = { Cloth = 1, Metal = 1 }
-- M_CAMERA (Camera): 1 Metal + 1 Battery
MARKET_COSTS.M_CAMERA = { Battery = 1, Metal = 1 }
-- M_LANTERN (Lantern): 2 Metal + 1 Wood
MARKET_COSTS.M_LANTERN = { Metal = 2, Wood = 1 }
-- M_FIRE_KIT (Fire Starter Kit): 1 Wood + 1 Cloth + 1 Metal
MARKET_COSTS.M_FIRE_KIT = { Cloth = 1, Metal = 1, Wood = 1 }
-- M_TOOLBOX (Toolbox): 2 Metal + 1 Wood
MARKET_COSTS.M_TOOLBOX = { Metal = 2, Wood = 1 }
-- M_DUCT_TAPE (Duct Tape): 1 Cloth
MARKET_COSTS.M_DUCT_TAPE = { Cloth = 1 }
-- M_SPORTS_DRINK (Sports Drink): 1 Energy Drink
MARKET_COSTS.M_SPORTS_DRINK = { EnergyDrink = 1 }
-- M_PROTEIN_BAR (Protein Bar): 2 Food
MARKET_COSTS.M_PROTEIN_BAR = { Food = 2 }
-- M_PORTABLE_CROCKPOT (Portable Crockpot): 2 Metal + 2 Wood + 1 Cloth
MARKET_COSTS.M_PORTABLE_CROCKPOT = { Cloth = 1, Metal = 2, Wood = 2 }
-- M_WHISTLE (Whistle): 1 Metal
MARKET_COSTS.M_WHISTLE = { Metal = 1 }
-- M_KEYS (House Keys): cost "Free at start (drawn by James)" -> no token-resource costs
MARKET_COSTS.M_KEYS = {}
-- M_PEPPER_SPRAY (Pepper Spray): 1 Cloth + 1 Metal
MARKET_COSTS.M_PEPPER_SPRAY = { Cloth = 1, Metal = 1 }
-- M_FIRST_GENERATION_PHONE (Old Cellphone): 1 Metal + 1 Battery
MARKET_COSTS.M_FIRST_GENERATION_PHONE = { Battery = 1, Metal = 1 }
-- M_DOG_LEASH (Dog Leash): 1 Cloth + 1 Metal
MARKET_COSTS.M_DOG_LEASH = { Cloth = 1, Metal = 1 }
-- M_HAIRSPRAY (Hairspray + Lighter): 1 Metal + 1 Energy Drink
MARKET_COSTS.M_HAIRSPRAY = { EnergyDrink = 1, Metal = 1 }
-- M_CHAINSAW (Chainsaw): 3 Metal + 1 Wood + 1 Battery
MARKET_COSTS.M_CHAINSAW = { Battery = 1, Metal = 3, Wood = 1 }
-- M_REINFORCED_DOOR (Reinforced Door): 2 Wood + 2 Metal
MARKET_COSTS.M_REINFORCED_DOOR = { Metal = 2, Wood = 2 }
-- M_BARRICADE (Barricade): 2 Wood + 1 Metal
MARKET_COSTS.M_BARRICADE = { Metal = 1, Wood = 2 }
-- M_CAMPFIRE (Campfire): 2 Wood + 1 Cloth
MARKET_COSTS.M_CAMPFIRE = { Cloth = 1, Wood = 2 }
-- M_WATCHTOWER (Watchtower): 3 Wood + 2 Metal
MARKET_COSTS.M_WATCHTOWER = { Metal = 2, Wood = 3 }
-- M_RABBIT_FOOT (Rabbit's Foot): 1 Cloth + 1 Food
MARKET_COSTS.M_RABBIT_FOOT = { Cloth = 1, Food = 1 }
-- M_THERMOS (Thermos): 1 Metal + 1 Cloth
MARKET_COSTS.M_THERMOS = { Cloth = 1, Metal = 1 }
-- M_ENERGY_DRINK_CASE (Case of Energy Drinks): 2 Energy Drink + 1 Cloth
MARKET_COSTS.M_ENERGY_DRINK_CASE = { Cloth = 1, EnergyDrink = 2 }
-- M_SCHOOL_BELL (School Bell): 1 Metal
MARKET_COSTS.M_SCHOOL_BELL = { Metal = 1 }
-- M_LOCKPICK (Lockpick Set): 1 Metal + 1 Cloth
MARKET_COSTS.M_LOCKPICK = { Cloth = 1, Metal = 1 }
-- M_FRIENDSHIP_BRACELET (Friendship Bracelet): 1 Cloth
MARKET_COSTS.M_FRIENDSHIP_BRACELET = { Cloth = 1 }
-- M_NOTEBOOK (Notebook & Pen): 1 Cloth + 1 Wood
MARKET_COSTS.M_NOTEBOOK = { Cloth = 1, Wood = 1 }
-- M_PRY_BAR (Pry Bar): 1 Metal
MARKET_COSTS.M_PRY_BAR = { Metal = 1 }
-- M_BICYCLE (Bicycle): 2 Metal + 1 Wood + 1 Cloth
MARKET_COSTS.M_BICYCLE = { Cloth = 1, Metal = 2, Wood = 1 }
