-- notebook_data.lua
-- AUTO-GENERATED by scripts/generate_notebook.py — do not edit by hand.
-- Source: content/notebook/*.md + content/help/glossary.md — the in-game
-- Notebook tabs and Help panel text are these files, converted to plain
-- text. Edit the markdown, rerun the generator, rebuild the save.

-- Notebook tab 'Quick Start' (populateNotebook, ui_help.lua)
-- from content/notebook/quickstart.md
NOTEBOOK_QUICKSTART = [==[
QUICK START — STARVE NO MORE

GOAL
Survive 7 nights as a team. The Doom track must stay below 30. If everyone is Down at the same time, you lose. And when The Source arrives in the Final Hours, you must destroy it — if the final boss still stands at the end of Day 7, the neighborhood is lost.

EACH DAY
1. Dawn — Doom advances — faster if threats (and especially bosses) were left on the map. A Dawn card flips. Read it; do what it says.
2. Day — Each player takes 3 actions in turn order: Move, Gather, Craft, Cook, Fight, Rest, or Cleanse.
3. Dusk — Last chance to move: scramble 1 tile (costs 1 Hunger) or stay. You sleep where you stand.
4. Night — Threats are drawn at each occupied tile. Fight or take damage. Sleep restores stats — but a house only sleeps two comfortably.
5. Tick — Everyone loses 1 Hunger and 1 Sanity. Day Counter advances.

THREE STATS
- ❤ Health — go to 0 = Down (ghost).
- 🍴 Hunger — keeps you above zero or you starve.
- 🧠 Sanity — go to 0 = Down (lost).

Below 3 in any stat: bad things happen. Read your player board.

TRADE
Players in the same tile may trade freely on either's turn — no action cost. Talk. Plan. The game wants you to.

YOUR SIGNATURE
Every character has one once-per-game Signature Move (the purple button on your Action Bar). It's big, it's named, and you only get it once — save it for the moment the week turns.

LIGHT
Anywhere without a light source at night = a Charlie attack (2 Sanity + 1 Health — and she hits harder every consecutive dark night). Carry a Flashlight (Battery), a Lantern (Fire), or sleep next to a Fire.

TIP
Hover anything for its rule. Click "?" at the top of the screen for the Help menu. Click "What now?" if you don't know what to do.

You don't need to read the rulebook. The game will prompt you.]==]

-- Notebook tab 'Full Rules'
-- from content/notebook/full_rules.md
NOTEBOOK_FULL_RULES = [==[
STARVE NO MORE — FULL RULES (ABRIDGED)

This is the in-game reference. The full design intent is in StarveNoMoreDesignConcept.md. Day-to-day play is driven by the on-screen Phase Banner and the Help menu (?); this Notebook is your fallback.

SETUP

1. Click Setup Game on the Setup Pedestal.
2. Pick a path graph (Compact / Sprawl / Linear).
3. Optional variants (both off = standard game): Rotation turns and Random Scenario (see Variants below).
4. Each player picks a character. Read your one-time character briefing — that tells you what makes you different.
5. Day 1 begins. The Phase Banner takes over.

TURN STRUCTURE

DAWN
- Day Counter advances.
- Doom advances by phase rate (adjusted by player count, see Help → Doom), plus +1 for each Threat still on the map (festering, max +3), plus +2 for each Boss / +1 for the Treeguard (no cap).
- Moonlit Salvage: anyone who survived the night at a sport court gathers 2 resources from that court's bag.
- Dares: some early-week Dawn cards carry an *optional* temptation alongside their effect — extra loot for extra risk. The card states the terms; take it or leave it.
- The Wrongness: one Dawn card places a face-down, unresolved Threat on the map. Enter its tile to resolve it — or it resolves itself at the next Dawn, where it stands.
- Reveal top of the active Phase deck. Apply effects.

DAY
Each player has 3 actions, taken as one turn (default) — or, with the Rotation variant, 1 action per visit cycling around the table until all are spent (pass after acting = keep the rest banked; pass without acting = forfeit them). Choose any:
- Move (1) — adjacent tile. Costs 1 Hunger. Rayman moves 2 spaces.
- Gather (1) — draw 1 resource at this tile.
- Craft (1) — buy an Item from the Market.
- Cook (1) — at a Crockpot, prepare a Recipe.
- Fight (1) — attack a Threat at this tile.
- Rest (1) — +1 Hunger or +2 Sanity. Own house: also +1 Health.
- Pry (free) — with a Crowbar, Lockpick, or Pry Bar: open a sealed thing at your tile for its printed reward (sealed Threat cards; the Sealed Basement at Ellie & Luca's House).
- Cleanse (1) — pay 1 Wood + 1 Cloth + 1 Battery + 1 Energy Drink → Doom -2.
- Trade (free) — same tile, both consent.

DUSK
Last chance to move: each character may scramble 1 tile (costs 1 Hunger, once per character), or stay. You sleep where you stand. Declarations are public — argue it out.

NIGHT
For each occupied tile, least-populated first:
- Draw threats per the location's threat rate (modified by Doom thresholds).
- Resolve combat or damage.
- Charlie check: no light source = 2 Sanity + 1 Health. Each consecutive night in darkness, +1 to both. A night with light resets her.
- Storytelling: Comfort Items used here for shared Sanity gain.
- Sleep — a house sleeps two comfortably; each sleeper beyond the second gets the floor (no regen):
  - Own house: +1 Sanity, +1 Hunger, +1 Health.
  - Someone else's house with company: +1 Sanity.
  - Alone in a non-house: nothing (often worse) — but court survivors salvage 2 resources at Dawn.

TICK
- Every character loses 1 Hunger and 1 Sanity.
- Rayman loses 2 Hunger.
- Coco's allies lose 1 less Sanity here. Luca's allies gain +1 Sanity. Ellie's house gains +1 Sanity.
- Pass First Player.
- Check victory/defeat.

COMBAT

- Attacker rolls dice = base attack + weapon + modifiers.
- Each 5 or 6 = 1 hit (1 damage to enemy).
- Fumble: a 1 costs 1 Health only if the roll had no hits (max 1 per roll).
- Press the Attack: landed a hit? You may pay 1 Sanity to roll one bonus die — 5–6 deals 1 more damage and you may press again; 1–4 ends the streak. Press dice never fumble. The enemy doesn't strike back until you stop. Pressing can drop you to 0 Sanity — you go Lost, mid-fight.
- When you stop (or whiff), the enemy attacks back: roll its attack dice; each 5–6 = 1 damage.
- Group combat sums dice; return damage rotates highest-Health first. Each fighter may press, paying their own Sanity.
- Flee (always legal, even starving): move 1 tile away, pay 1 Sanity. The threat stays — and festers at Dawn.
- Boss kills pay out: Deerclops Doom −2, Eye of Terror Doom −3, plus 3 resources spill at the tile and the boss's Trophy (a unique team power).
- Signature Moves: every character has one once-per-game named move (see the Character Reference tab) — fired from the Signature button, each paying an off-stat cost.
- The Source splits: the final boss's HP is script-tracked; the first time it drops to 5 HP or below, two Terror Beaks peel off to adjacent tiles (ordinary threats — they fight, flee, and fester normally).

THE TREEGUARD (PHASE 2.5)

At Dusk of Day 4 — every game — a Treeguard (HP 5, Atk 2) wakes at a random sport court. While it stands, no one may Gather at its court, and it festers Doom +1 each Dawn. Fight it (defeat: +1 Sanity each, salvage 3 Wood) or appease it (1 action + 2 Wood at its tile — it sleeps, no reward).

DEATH AND REVIVAL

- Health 0 = Down. Sanity 0 = Lost (also Down).
- Going Down feeds the dark: Doom +1.
- Flip standee to ghost. Cannot act. Drifts 1 tile per round. May whisper one word per round.
- To revive: a Telltale Heart token (cooked at the Crockpot for 1 Cloth + 1 Battery + 1 Food + 2 Health from the cook).
- Revived character returns at half maximums.

DOOM

The Doom track runs 0–30. At 30, the team loses. It advances each Dawn by the phase rate, +1 per festering threat left on the map (max +3), +2 per boss / +1 for the Treeguard (no cap — bosses charge interest every Dawn they stand), and +1 whenever a character goes Down. Thresholds:
- 10: night threats +1
- 15: Scarcity — crafts cost +1 extra resource (your choice of type)
- 20: all -1 Sanity at Tick
- 25: bosses can appear in any phase — and Nothing Left to Lose: everyone gets +1 attack die, and Rest heals +1 Health anywhere (non-stacking with the at-home bonus). Go down swinging.
- 30: defeat

Push back Doom by Cleansing — or by killing a phase boss (Deerclops −2, Eye −3).

VICTORY

Survive Day 7 with Doom < 30 — and The Source must be destroyed. If the final boss still stands at the end of Day 7, the team loses, whatever the Doom track says.

Day 7 opens on The Last Dawn — a fixed Dawn with no penalty ("the sky is trying to lighten; survive until it's over"). No card is drawn.

Bonus achievements:
- Pristine — all 5 alive.
- Truth — 3 Clue cards collected.
- Hero — defeat all 3 phase bosses (Deerclops, Eye of Terror, The Source).

VARIANTS (OPTIONAL, CHOSEN AT SETUP)

- Rotation turns — during Day, take 1 action per visit instead of all 3 at once; priority cycles until every action is spent. Shorter waits between your decisions at 4–5 players. Pass after acting keeps your remaining actions; pass without acting forfeits them.
- Random Scenario — one week-long twist revealed at setup and shown in the "Rules in effect" panel all game: The Long Winter (hunger is brutal), The Scorching Summer, The Rotting Autumn, The False Spring, Total Blackout (Fire is the only light), Strict Rationing, The Full Moon (no Charlie, harder threats), The Shortcut. Recommended after your first game.]==]

-- Notebook tab 'Characters'
-- from content/notebook/character_reference.md
NOTEBOOK_CHARACTERS = [==[
CHARACTER REFERENCE

Every character has one Signature — a once-per-game named move, fired from the Signature button. Save it for the moment it matters.

JAMES — THE GAMER
- Stats: Health 8 / Hunger 6 / Sanity 10
- Gaming Reflexes: once per turn reroll one of your own dice.
- Pattern Recognition: once per day peek the top of any deck.
- All-Nighter (Signature, 1×): take 3 extra actions this turn; lose 3 Sanity at the next Tick.
- Wired (constraint): consume 1 Energy Drink per day or lose 2 Sanity at night.
- Starting hand: Energy Drink ×2, Pocketknife, Flashlight, Headphones.

COCO — THE ANGEL
- Stats: Health 6 / Hunger 8 / Sanity 12
- Calming Presence: allies at her tile lose 1 less Sanity at Tick.
- Touch of Hope (Signature, 1×): heal any character +4 Health, anywhere on the map.
- Light in the Dark: never triggers Charlie attacks.
- No Home (constraint): end Night alone in a non-house = -3 Sanity.
- Starting hand: First Aid Kit, Comfort Blanket, Hopeful Tea, Spare Phone Battery, Friendship Bracelet.

RAYMAN — THE BASKETBALL PLAYER
- Stats: Health 12 / Hunger 10 / Sanity 6
- Speed: Move +1 space per Move action.
- Court Master: +1 attack die at the Basketball Court.
- Backboard Block: Defend action shields adjacent allies for one round.
- Posterize (Signature, 1×): instantly defeat one non-boss threat at your tile — no roll, no counter. The noise: your tile draws +1 Threat tonight.
- Big Appetite: lose 2 Hunger per day.
- Loud: if Rayman moved at all today, the location where he spends the Night draws +1 Threat (once — it doesn't stack).
- Starting hand: Basketball, Sports Drink ×2, Athletic Tape, Whistle.

ELLIE — THE COOK
- Stats: Health 8 / Hunger 10 / Sanity 8
- Crockpot Master: Recipes need 1 fewer ingredient (min 1).
- Comfort Food: when Ellie shares cooked food, eaters gain +1 extra Hunger and +1 extra Sanity.
- Knows the Pantry: at her own house, search resource bag for a specific token.
- The Feast (Signature, 1×): at a Crockpot, cook any number of recipes in a single action (ingredients still required); consumes ALL your held Food.
- Particular Eater (constraint): cannot eat raw food.
- Starting hand: Crockpot, Soup Recipe, Cooking Knife, Pantry Key, Apron.

LUCA — THE ORATOR
- Stats: Health 7 / Hunger 8 / Sanity 10
- Rally: once per turn give an adjacent ally a free non-movement action.
- Calm Words: at his tile, on a Sanity-loss event, roll d6 — 4+ negates the loss for everyone here.
- Storyteller: allies at his tile +1 Sanity at Night.
- The Speech (Signature, 1×): every character, anywhere, +2 Sanity. Only usable while an ally is Down or below 3 Sanity.
- Needs an Audience (constraint): alone, his Sanity does not regenerate.
- Starting hand: Notebook, Loud Whistle, Pep Talk, Reading Lamp, Toolbox.]==]

-- Help panel 'Quick Start' tab (refreshHelpPanel, ui_help.lua)
-- from content/notebook/quickstart.md
HELP_QUICKSTART = [==[
QUICK START — STARVE NO MORE

GOAL
Survive 7 nights as a team. The Doom track must stay below 30. If everyone is Down at the same time, you lose. And when The Source arrives in the Final Hours, you must destroy it — if the final boss still stands at the end of Day 7, the neighborhood is lost.

EACH DAY
1. Dawn — Doom advances — faster if threats (and especially bosses) were left on the map. A Dawn card flips. Read it; do what it says.
2. Day — Each player takes 3 actions in turn order: Move, Gather, Craft, Cook, Fight, Rest, or Cleanse.
3. Dusk — Last chance to move: scramble 1 tile (costs 1 Hunger) or stay. You sleep where you stand.
4. Night — Threats are drawn at each occupied tile. Fight or take damage. Sleep restores stats — but a house only sleeps two comfortably.
5. Tick — Everyone loses 1 Hunger and 1 Sanity. Day Counter advances.

THREE STATS
- ❤ Health — go to 0 = Down (ghost).
- 🍴 Hunger — keeps you above zero or you starve.
- 🧠 Sanity — go to 0 = Down (lost).

Below 3 in any stat: bad things happen. Read your player board.

TRADE
Players in the same tile may trade freely on either's turn — no action cost. Talk. Plan. The game wants you to.

YOUR SIGNATURE
Every character has one once-per-game Signature Move (the purple button on your Action Bar). It's big, it's named, and you only get it once — save it for the moment the week turns.

LIGHT
Anywhere without a light source at night = a Charlie attack (2 Sanity + 1 Health — and she hits harder every consecutive dark night). Carry a Flashlight (Battery), a Lantern (Fire), or sleep next to a Fire.

TIP
Hover anything for its rule. Click "?" at the top of the screen for the Help menu. Click "What now?" if you don't know what to do.

You don't need to read the rulebook. The game will prompt you.]==]

-- Help panel 'Glossary' tab
-- from content/help/glossary.md
HELP_GLOSSARY = [==[
GLOSSARY

STATS
- Health (❤) — physical damage. Health 0 = Down (ghost).
- Hunger (🍴) — depletes 1 each day. Hunger 0 = lose 1 Health per Tick.
- Sanity (🧠) — depletes from darkness, isolation, weird events. Sanity 0 = Down (lost).

STAT THRESHOLDS
- Below 3 in any stat: Bad Things Happen.
  - Low Health: Move costs +1 action.
  - Low Hunger: cannot Fight; cannot use [Effort] Items. (You may always Flee.)
  - Low Sanity: Haunted — each Dawn, draw 1 Threat at your tile. Only you may fight or flee it; allies can't help. Discard when resolved; it never festers.

RESOURCES
- Wood, Metal, Cloth, Food, Energy Drink, Battery — see Resource bag tooltips.
- Hand limit: 5 Items + 8 Resources. Excess is dropped at your tile.

LIGHT SOURCES
- Flashlight — needs Battery; some Dawn cards disable.
- Lantern / Campfire / Hairspray flame — Fire (more reliable).
- Without light at night: Charlie attacks — 2 Sanity + 1 Health. Each consecutive night in darkness she grows bolder: +1 to both. A night with light resets her interest.

PHASES
- Phase 1 (Days 1–2) — Dusk of the Week.
- Phase 2 (Days 3–4) — Strange Days. Mid-tier boss arrives Day 4 (Deerclops).
- Phase 2.5 (Dusk of Day 4, always) — The Treeguard wakes at a random sport court.
- Phase 3 (Day 5) — Long Nights. Heavy boss arrives (Eye of Terror).
- Phase 4 (Days 6–7) — Final Hours. The Source arrives — it must be destroyed before Day 7 ends.

VARIANTS (OPTIONAL, CHOSEN AT SETUP)
- Rotation turns — Day actions are taken 1 per visit, cycling around the table, instead of 3 at once. Pass after acting = keep your remaining actions banked; pass without acting = forfeit them.
- Scenario — one week-long world modifier revealed at setup (e.g. The Long Winter, Total Blackout). Its rules stay in the "Rules in effect" panel all game. One per game, off by default.

TREEGUARD (MINI-BOSS)
- Wakes at Dusk of Day 4 at a random sport court. HP 5, Attack 2.
- While it stands: no Gathering at its court, and it festers Doom +1 each Dawn.
- Fight: defeat gives +1 Sanity each and 3 Wood salvage.
- Appease: 1 action + 2 Wood at its tile — it returns to sleep. No reward, no fight.
- Not counted for the Hero Run (mini-boss, no Trophy).

ACTIONS
- Move (1 action, 1 Hunger).
- Gather (1 action) — draw a resource.
- Craft (1 action) — claim a Market card.
- Cook (1 action) — at a Crockpot.
- Fight (1 action) — combat at this tile.
- Rest (1 action) — +1 Hunger or +2 Sanity. Own house: also +1 Health.
- Cleanse (1 action) — Doom -2; spend the resource bundle.
- Pry (free action) — open a sealed thing at your tile; needs a Crowbar, Lockpick, or Pry Bar.
- Trade (free) — same tile, both consent.
- Flee (always legal, even starving) — move 1 tile away from a threat, pay 1 Sanity. The threat stays and festers at Dawn.
- Press the Attack — after landing a hit in combat, pay 1 Sanity to roll one bonus die (5–6 = 1 more damage, press again; 1–4 = streak ends, enemy counters). Press dice never fumble. Pressing can drop you to 0 Sanity — you go Lost mid-fight.
- Boss rewards — killing a phase boss rebates Doom (Deerclops −2, Eye −3), spills 3 resources at its tile, and awards its Trophy (a unique team power).
- Signature Move — every character's once-per-game named move (Signature button): James's All-Nighter, Coco's Touch of Hope, Rayman's Posterize, Ellie's Feast, Luca's Speech. Each pays an off-stat cost.
- Dare — an *optional* hook on some early-week Dawn cards: a temptation the team may take or decline (extra loot for extra risk). Never mandatory; the card and the Rules panel state the terms.
- Pry — a free action with a Crowbar, Lockpick, or Pry Bar: open a sealed thing at your tile for its printed reward. Sealed Threat cards and the Sealed Basement (at Ellie & Luca's House from setup) all open this way.
- The Wrongness — a face-down, unresolved Threat placed at a tile by a Dawn card. Someone can go look (it resolves on entering the tile) — or it resolves at the next Dawn, where it stands. It doesn't fester while face-down.
- Source split — the first time The Source drops to 5 HP or below, two Terror Beaks peel off to adjacent tiles. Its HP is script-tracked from arrival.

SEVERITY DOTS
- ●○○○○ atmospheric • ●●○○○ minor • ●●●○○ combat/lasting • ●●●●○ phase-shift • ●●●●● apocalyptic.

DOWN STATE
- Flip standee. Cannot act. Drift 1 tile per round. May say one word per round.
- Going Down feeds the dark: Doom +1.
- Revive: spend a Telltale Heart at your tile. Reviver pays 2 Health. Revived returns at half max.

TELLTALE HEART
- A Recipe (not a Market Item). Cook 1 Cloth + 1 Battery + 1 Food + 2 cook Health → 1 Heart token.
- 5 Hearts max in supply. Used Hearts return to the supply pool.

DOOM TRACK
- Public 0–30 track. At 30, the team loses.
- Advances each Dawn by the phase rate, +1 per threat still on the map (festering, max +3), +2 per boss / +1 for the Treeguard (no cap), and +1 whenever a character goes Down.
- Thresholds: 10 (threats +1), 15 (crafts +1 resource), 20 (-1 Sanity Tick), 25 (bosses any phase + Nothing Left to Lose: +1 attack die for everyone, Rest heals +1 Health anywhere).
- Cleanse (Day action) reduces Doom by 2.

DUSK SCRAMBLE
- At Dusk, each character may move 1 tile for 1 Hunger (once). You sleep where you stand.

CROWDED FLOOR
- A house sleeps two comfortably. Each sleeper beyond the second gets the floor: no sleep regeneration. Beds go to owners first, then whoever needs them most.

MOONLIT SALVAGE
- Spend the night at a sport court and survive to Dawn: gather 2 resources from that court's bag. The courts are richest when the world sleeps.

VICTORY AND DEFEAT
- Survive Day 7 with Doom < 30 to win — and if The Source has arrived, it must be destroyed. While it stands at the end of Day 7, there is no victory.
- The Last Dawn — Day 7's Dawn is fixed, not drawn: no penalty, just the finish line.
- Pristine Run — all 5 alive.
- Truth Run — 3 Clue cards collected.
- Hero Run — all 3 phase bosses defeated (Deerclops, Eye of Terror, The Source; the Treeguard doesn't count).
- Defeats: Doom hits 30; all alive characters Down at the same instant; The Source still standing at the end of Day 7.]==]
