-- threat_types.lua
-- AUTO-GENERATED by scripts/generate_threat_types.py — do not edit by hand.
-- Source: content/cards_threats.csv (name + type columns)
--
-- THREAT_TYPE_BY_NAME[nickname] = "Hard" | "Soft" | "Persistent"
-- Used by the Night Sounds dusk peek (day_loop.lua): a face-down deck
-- only exposes nicknames, so type is looked up here.

THREAT_TYPE_BY_NAME = {}

THREAT_TYPE_BY_NAME["Shadow Stalker"] = "Hard"  -- T_SHADOW_STALKER
THREAT_TYPE_BY_NAME["Hollow Spectator"] = "Hard"  -- T_HOLLOW_SPECTATOR
THREAT_TYPE_BY_NAME["Terror Beak"] = "Hard"  -- T_TERROR_BEAK
THREAT_TYPE_BY_NAME["Spider Thing"] = "Hard"  -- T_SPIDER_THING
THREAT_TYPE_BY_NAME["Your Roommate (Wrong)"] = "Hard"  -- T_ROOMMATE
THREAT_TYPE_BY_NAME["The Neighbor"] = "Hard"  -- T_THE_NEIGHBOR
THREAT_TYPE_BY_NAME["A Howling Outside"] = "Soft"  -- T_HOWLING
THREAT_TYPE_BY_NAME["The Power Flickers"] = "Soft"  -- T_POWER_FLICKER
THREAT_TYPE_BY_NAME["The Doorbell Rang"] = "Soft"  -- T_RUNG_DOORBELL
THREAT_TYPE_BY_NAME["Food Gone Wrong"] = "Soft"  -- T_FOOD_GONE_WRONG
THREAT_TYPE_BY_NAME["Whispers Behind the Walls"] = "Soft"  -- T_WHISPERS
THREAT_TYPE_BY_NAME["Lost Memories"] = "Soft"  -- T_LOST_MEMORIES
THREAT_TYPE_BY_NAME["The Grue (Charlie)"] = "Hard"  -- T_THE_GRUE
THREAT_TYPE_BY_NAME["Lurker"] = "Persistent"  -- T_LURKER
THREAT_TYPE_BY_NAME["Hungry Dog"] = "Persistent"  -- T_HUNGRY_DOG
THREAT_TYPE_BY_NAME["Cracked Floor"] = "Persistent"  -- T_CRACKED_FLOOR
THREAT_TYPE_BY_NAME["A Buzzing in Your Head"] = "Soft"  -- T_BUZZING
THREAT_TYPE_BY_NAME["The Lights Cut Out"] = "Soft"  -- T_LIGHTS_OUT
THREAT_TYPE_BY_NAME["Voices Calling Names"] = "Soft"  -- T_VOICES
THREAT_TYPE_BY_NAME["Breathing in the Wall"] = "Soft"  -- T_BREATHING
THREAT_TYPE_BY_NAME["A Phone Rings"] = "Soft"  -- T_PHONE_RINGS
THREAT_TYPE_BY_NAME["Roaches in the Pantry"] = "Soft"  -- T_ROACHES
THREAT_TYPE_BY_NAME["The Door at the Back"] = "Hard"  -- T_THE_DOOR
THREAT_TYPE_BY_NAME["A Child's Shadow"] = "Hard"  -- T_CHILD_SHADOW
THREAT_TYPE_BY_NAME["Crawling Hand"] = "Hard"  -- T_CRAWLING_HAND
THREAT_TYPE_BY_NAME["Black Dog"] = "Hard"  -- T_BLACK_DOG
THREAT_TYPE_BY_NAME["A Stairway Spiraling Down"] = "Persistent"  -- T_SPIRAL
THREAT_TYPE_BY_NAME["A Twin Walks Past You"] = "Soft"  -- T_THE_TWIN
THREAT_TYPE_BY_NAME["A Friend Bleeding"] = "Soft"  -- T_FRIEND_BLOOD
THREAT_TYPE_BY_NAME["A Fire That Won't Take"] = "Soft"  -- T_FIRE_OUT
THREAT_TYPE_BY_NAME["Fog Bank"] = "Persistent"  -- T_FOG_BANK
THREAT_TYPE_BY_NAME["The Nest"] = "Persistent"  -- T_NEST
THREAT_TYPE_BY_NAME["Contaminated Water"] = "Persistent"  -- T_CONTAMINATED
THREAT_TYPE_BY_NAME["The Locked Room"] = "Persistent"  -- T_LOCKED_ROOM
THREAT_TYPE_BY_NAME["The Mimic"] = "Hard"  -- T_MIMIC
THREAT_TYPE_BY_NAME["Rat Swarm"] = "Hard"  -- T_SWARM
THREAT_TYPE_BY_NAME["The Scarecrow"] = "Hard"  -- T_SCARECROW
THREAT_TYPE_BY_NAME["Something Dripping from Above"] = "Soft"  -- T_CEILING_DRIP
THREAT_TYPE_BY_NAME["The Doppelganger"] = "Hard"  -- T_DOPPELGANGER
THREAT_TYPE_BY_NAME["Wall Crawler"] = "Hard"  -- T_WALL_CRAWLER
THREAT_TYPE_BY_NAME["The Glass Child"] = "Hard"  -- T_GLASS_CHILD
THREAT_TYPE_BY_NAME["The Furnace Woke Up"] = "Soft"  -- T_FURNACE
THREAT_TYPE_BY_NAME["Every Clock Stopped"] = "Soft"  -- T_CLOCK_STOPS
THREAT_TYPE_BY_NAME["Roots Through the Floor"] = "Persistent"  -- T_ROOTS
THREAT_TYPE_BY_NAME["The Echo"] = "Soft"  -- T_ECHO
THREAT_TYPE_BY_NAME["Moth Cloud"] = "Soft"  -- T_MOTH_CLOUD
THREAT_TYPE_BY_NAME["The Thing in the Attic"] = "Hard"  -- T_THING_IN_ATTIC
THREAT_TYPE_BY_NAME["The Watcher"] = "Persistent"  -- T_WATCHER
THREAT_TYPE_BY_NAME["The Sealed Shed"] = "Persistent"  -- T_SEALED_SHED
THREAT_TYPE_BY_NAME["The Sealed Locker"] = "Persistent"  -- T_SEALED_LOCKER
THREAT_TYPE_BY_NAME["The Sealed Car"] = "Persistent"  -- T_SEALED_CAR
