-- threat_types.lua
-- AUTO-GENERATED by scripts/generate_threat_types.py — do not edit by hand.
-- Source: content/cards_threats.csv (name/type + pry_reward columns)
--
-- THREAT_TYPE_BY_ID[id] = "Hard" | "Soft" | "Persistent"
-- The authority behind identifyThreatType (night.lua). Every drawn
-- card carries its CSV id as a tag, so this is the lookup that always
-- works; the nickname mirror below is for handles that only expose a
-- name (the face-down deck peek).
THREAT_TYPE_BY_ID = {}

THREAT_TYPE_BY_ID.T_SHADOW_STALKER = "Hard"
THREAT_TYPE_BY_ID.T_HOLLOW_SPECTATOR = "Hard"
THREAT_TYPE_BY_ID.T_TERROR_BEAK = "Hard"
THREAT_TYPE_BY_ID.T_SPIDER_THING = "Hard"
THREAT_TYPE_BY_ID.T_ROOMMATE = "Hard"
THREAT_TYPE_BY_ID.T_THE_NEIGHBOR = "Hard"
THREAT_TYPE_BY_ID.T_HOWLING = "Soft"
THREAT_TYPE_BY_ID.T_POWER_FLICKER = "Soft"
THREAT_TYPE_BY_ID.T_RUNG_DOORBELL = "Soft"
THREAT_TYPE_BY_ID.T_FOOD_GONE_WRONG = "Soft"
THREAT_TYPE_BY_ID.T_WHISPERS = "Soft"
THREAT_TYPE_BY_ID.T_LOST_MEMORIES = "Soft"
THREAT_TYPE_BY_ID.T_THE_GRUE = "Hard"
THREAT_TYPE_BY_ID.T_LURKER = "Persistent"
THREAT_TYPE_BY_ID.T_HUNGRY_DOG = "Persistent"
THREAT_TYPE_BY_ID.T_CRACKED_FLOOR = "Persistent"
THREAT_TYPE_BY_ID.T_BUZZING = "Soft"
THREAT_TYPE_BY_ID.T_LIGHTS_OUT = "Soft"
THREAT_TYPE_BY_ID.T_VOICES = "Soft"
THREAT_TYPE_BY_ID.T_BREATHING = "Soft"
THREAT_TYPE_BY_ID.T_PHONE_RINGS = "Soft"
THREAT_TYPE_BY_ID.T_ROACHES = "Soft"
THREAT_TYPE_BY_ID.T_THE_DOOR = "Hard"
THREAT_TYPE_BY_ID.T_CHILD_SHADOW = "Hard"
THREAT_TYPE_BY_ID.T_CRAWLING_HAND = "Hard"
THREAT_TYPE_BY_ID.T_BLACK_DOG = "Hard"
THREAT_TYPE_BY_ID.T_SPIRAL = "Persistent"
THREAT_TYPE_BY_ID.T_THE_TWIN = "Soft"
THREAT_TYPE_BY_ID.T_FRIEND_BLOOD = "Soft"
THREAT_TYPE_BY_ID.T_FIRE_OUT = "Soft"
THREAT_TYPE_BY_ID.T_FOG_BANK = "Persistent"
THREAT_TYPE_BY_ID.T_NEST = "Persistent"
THREAT_TYPE_BY_ID.T_CONTAMINATED = "Persistent"
THREAT_TYPE_BY_ID.T_LOCKED_ROOM = "Persistent"
THREAT_TYPE_BY_ID.T_MIMIC = "Hard"
THREAT_TYPE_BY_ID.T_SWARM = "Hard"
THREAT_TYPE_BY_ID.T_SCARECROW = "Hard"
THREAT_TYPE_BY_ID.T_CEILING_DRIP = "Soft"
THREAT_TYPE_BY_ID.T_DOPPELGANGER = "Hard"
THREAT_TYPE_BY_ID.T_WALL_CRAWLER = "Hard"
THREAT_TYPE_BY_ID.T_GLASS_CHILD = "Hard"
THREAT_TYPE_BY_ID.T_FURNACE = "Soft"
THREAT_TYPE_BY_ID.T_CLOCK_STOPS = "Soft"
THREAT_TYPE_BY_ID.T_ROOTS = "Persistent"
THREAT_TYPE_BY_ID.T_ECHO = "Soft"
THREAT_TYPE_BY_ID.T_MOTH_CLOUD = "Soft"
THREAT_TYPE_BY_ID.T_THING_IN_ATTIC = "Hard"
THREAT_TYPE_BY_ID.T_WATCHER = "Persistent"
THREAT_TYPE_BY_ID.T_SEALED_SHED = "Persistent"
THREAT_TYPE_BY_ID.T_SEALED_LOCKER = "Persistent"
THREAT_TYPE_BY_ID.T_SEALED_CAR = "Persistent"

-- THREAT_TYPE_BY_NAME[nickname] = "Hard" | "Soft" | "Persistent"
-- Used by the Night Sounds dusk peek (day_loop.lua): a face-down deck
-- only exposes nicknames, so type is looked up here.

THREAT_TYPE_BY_NAME = {}

THREAT_TYPE_BY_NAME["Shadow Stalker"] = "Hard"  -- T_SHADOW_STALKER
THREAT_TYPE_BY_NAME["Hollow Spectator"] = "Hard"  -- T_HOLLOW_SPECTATOR
THREAT_TYPE_BY_NAME["Terror Beak"] = "Hard"  -- T_TERROR_BEAK
THREAT_TYPE_BY_NAME["Spider Thing"] = "Hard"  -- T_SPIDER_THING
THREAT_TYPE_BY_NAME["Your Roommate (Wrong)"] = "Hard"  -- T_ROOMMATE
THREAT_TYPE_BY_NAME["The Neighbor"] = "Hard"  -- T_THE_NEIGHBOR
THREAT_TYPE_BY_NAME["A Howling Outside"] = "Soft"  -- T_HOWLING
THREAT_TYPE_BY_NAME["The Power Flickers"] = "Soft"  -- T_POWER_FLICKER
THREAT_TYPE_BY_NAME["The Doorbell Rang"] = "Soft"  -- T_RUNG_DOORBELL
THREAT_TYPE_BY_NAME["Food Gone Wrong"] = "Soft"  -- T_FOOD_GONE_WRONG
THREAT_TYPE_BY_NAME["Whispers Behind the Walls"] = "Soft"  -- T_WHISPERS
THREAT_TYPE_BY_NAME["Lost Memories"] = "Soft"  -- T_LOST_MEMORIES
THREAT_TYPE_BY_NAME["The Grue (Charlie)"] = "Hard"  -- T_THE_GRUE
THREAT_TYPE_BY_NAME["Lurker"] = "Persistent"  -- T_LURKER
THREAT_TYPE_BY_NAME["Hungry Dog"] = "Persistent"  -- T_HUNGRY_DOG
THREAT_TYPE_BY_NAME["Cracked Floor"] = "Persistent"  -- T_CRACKED_FLOOR
THREAT_TYPE_BY_NAME["A Buzzing in Your Head"] = "Soft"  -- T_BUZZING
THREAT_TYPE_BY_NAME["The Lights Cut Out"] = "Soft"  -- T_LIGHTS_OUT
THREAT_TYPE_BY_NAME["Voices Calling Names"] = "Soft"  -- T_VOICES
THREAT_TYPE_BY_NAME["Breathing in the Wall"] = "Soft"  -- T_BREATHING
THREAT_TYPE_BY_NAME["A Phone Rings"] = "Soft"  -- T_PHONE_RINGS
THREAT_TYPE_BY_NAME["Roaches in the Pantry"] = "Soft"  -- T_ROACHES
THREAT_TYPE_BY_NAME["The Door at the Back"] = "Hard"  -- T_THE_DOOR
THREAT_TYPE_BY_NAME["A Child's Shadow"] = "Hard"  -- T_CHILD_SHADOW
THREAT_TYPE_BY_NAME["Crawling Hand"] = "Hard"  -- T_CRAWLING_HAND
THREAT_TYPE_BY_NAME["Black Dog"] = "Hard"  -- T_BLACK_DOG
THREAT_TYPE_BY_NAME["A Stairway Spiraling Down"] = "Persistent"  -- T_SPIRAL
THREAT_TYPE_BY_NAME["A Twin Walks Past You"] = "Soft"  -- T_THE_TWIN
THREAT_TYPE_BY_NAME["A Friend Bleeding"] = "Soft"  -- T_FRIEND_BLOOD
THREAT_TYPE_BY_NAME["A Fire That Won't Take"] = "Soft"  -- T_FIRE_OUT
THREAT_TYPE_BY_NAME["Fog Bank"] = "Persistent"  -- T_FOG_BANK
THREAT_TYPE_BY_NAME["The Nest"] = "Persistent"  -- T_NEST
THREAT_TYPE_BY_NAME["Contaminated Water"] = "Persistent"  -- T_CONTAMINATED
THREAT_TYPE_BY_NAME["The Locked Room"] = "Persistent"  -- T_LOCKED_ROOM
THREAT_TYPE_BY_NAME["The Mimic"] = "Hard"  -- T_MIMIC
THREAT_TYPE_BY_NAME["Rat Swarm"] = "Hard"  -- T_SWARM
THREAT_TYPE_BY_NAME["The Scarecrow"] = "Hard"  -- T_SCARECROW
THREAT_TYPE_BY_NAME["Something Dripping from Above"] = "Soft"  -- T_CEILING_DRIP
THREAT_TYPE_BY_NAME["The Doppelganger"] = "Hard"  -- T_DOPPELGANGER
THREAT_TYPE_BY_NAME["Wall Crawler"] = "Hard"  -- T_WALL_CRAWLER
THREAT_TYPE_BY_NAME["The Glass Child"] = "Hard"  -- T_GLASS_CHILD
THREAT_TYPE_BY_NAME["The Furnace Woke Up"] = "Soft"  -- T_FURNACE
THREAT_TYPE_BY_NAME["Every Clock Stopped"] = "Soft"  -- T_CLOCK_STOPS
THREAT_TYPE_BY_NAME["Roots Through the Floor"] = "Persistent"  -- T_ROOTS
THREAT_TYPE_BY_NAME["The Echo"] = "Soft"  -- T_ECHO
THREAT_TYPE_BY_NAME["Moth Cloud"] = "Soft"  -- T_MOTH_CLOUD
THREAT_TYPE_BY_NAME["The Thing in the Attic"] = "Hard"  -- T_THING_IN_ATTIC
THREAT_TYPE_BY_NAME["The Watcher"] = "Persistent"  -- T_WATCHER
THREAT_TYPE_BY_NAME["The Sealed Shed"] = "Persistent"  -- T_SEALED_SHED
THREAT_TYPE_BY_NAME["The Sealed Locker"] = "Persistent"  -- T_SEALED_LOCKER
THREAT_TYPE_BY_NAME["The Sealed Car"] = "Persistent"  -- T_SEALED_CAR

-- Statlines per card id, for the scripted Fight action (doFightTarget,
-- actions.lua). hp 0 = not fightable (Soft events / hp-less Persistents).
THREAT_STATS = {}

THREAT_STATS.T_SHADOW_STALKER = { name = "Shadow Stalker", hp = 4, attack = 2 }
THREAT_STATS.T_HOLLOW_SPECTATOR = { name = "Hollow Spectator", hp = 3, attack = 1 }
THREAT_STATS.T_TERROR_BEAK = { name = "Terror Beak", hp = 2, attack = 2 }
THREAT_STATS.T_SPIDER_THING = { name = "Spider Thing", hp = 3, attack = 1 }
THREAT_STATS.T_ROOMMATE = { name = "Your Roommate (Wrong)", hp = 5, attack = 2 }
THREAT_STATS.T_THE_NEIGHBOR = { name = "The Neighbor", hp = 6, attack = 2 }
THREAT_STATS.T_HOWLING = { name = "A Howling Outside", hp = 0, attack = 0 }
THREAT_STATS.T_POWER_FLICKER = { name = "The Power Flickers", hp = 0, attack = 0 }
THREAT_STATS.T_RUNG_DOORBELL = { name = "The Doorbell Rang", hp = 0, attack = 0 }
THREAT_STATS.T_FOOD_GONE_WRONG = { name = "Food Gone Wrong", hp = 0, attack = 0 }
THREAT_STATS.T_WHISPERS = { name = "Whispers Behind the Walls", hp = 0, attack = 0 }
THREAT_STATS.T_LOST_MEMORIES = { name = "Lost Memories", hp = 0, attack = 0 }
THREAT_STATS.T_THE_GRUE = { name = "The Grue (Charlie)", hp = 0, attack = 0 }
THREAT_STATS.T_LURKER = { name = "Lurker", hp = 3, attack = 1 }
THREAT_STATS.T_HUNGRY_DOG = { name = "Hungry Dog", hp = 2, attack = 1 }
THREAT_STATS.T_CRACKED_FLOOR = { name = "Cracked Floor", hp = 0, attack = 0 }
THREAT_STATS.T_BUZZING = { name = "A Buzzing in Your Head", hp = 0, attack = 0 }
THREAT_STATS.T_LIGHTS_OUT = { name = "The Lights Cut Out", hp = 0, attack = 0 }
THREAT_STATS.T_VOICES = { name = "Voices Calling Names", hp = 0, attack = 0 }
THREAT_STATS.T_BREATHING = { name = "Breathing in the Wall", hp = 0, attack = 0 }
THREAT_STATS.T_PHONE_RINGS = { name = "A Phone Rings", hp = 0, attack = 0 }
THREAT_STATS.T_ROACHES = { name = "Roaches in the Pantry", hp = 0, attack = 0 }
THREAT_STATS.T_THE_DOOR = { name = "The Door at the Back", hp = 0, attack = 0 }
THREAT_STATS.T_CHILD_SHADOW = { name = "A Child's Shadow", hp = 2, attack = 1 }
THREAT_STATS.T_CRAWLING_HAND = { name = "Crawling Hand", hp = 1, attack = 1 }
THREAT_STATS.T_BLACK_DOG = { name = "Black Dog", hp = 3, attack = 2 }
THREAT_STATS.T_SPIRAL = { name = "A Stairway Spiraling Down", hp = 0, attack = 0 }
THREAT_STATS.T_THE_TWIN = { name = "A Twin Walks Past You", hp = 0, attack = 0 }
THREAT_STATS.T_FRIEND_BLOOD = { name = "A Friend Bleeding", hp = 0, attack = 0 }
THREAT_STATS.T_FIRE_OUT = { name = "A Fire That Won't Take", hp = 0, attack = 0 }
THREAT_STATS.T_FOG_BANK = { name = "Fog Bank", hp = 0, attack = 0 }
THREAT_STATS.T_NEST = { name = "The Nest", hp = 0, attack = 0 }
THREAT_STATS.T_CONTAMINATED = { name = "Contaminated Water", hp = 0, attack = 0 }
THREAT_STATS.T_LOCKED_ROOM = { name = "The Locked Room", hp = 0, attack = 0 }
THREAT_STATS.T_MIMIC = { name = "The Mimic", hp = 3, attack = 2 }
THREAT_STATS.T_SWARM = { name = "Rat Swarm", hp = 2, attack = 1 }
THREAT_STATS.T_SCARECROW = { name = "The Scarecrow", hp = 4, attack = 1 }
THREAT_STATS.T_CEILING_DRIP = { name = "Something Dripping from Above", hp = 0, attack = 0 }
THREAT_STATS.T_DOPPELGANGER = { name = "The Doppelganger", hp = 4, attack = 2 }
THREAT_STATS.T_WALL_CRAWLER = { name = "Wall Crawler", hp = 2, attack = 2 }
THREAT_STATS.T_GLASS_CHILD = { name = "The Glass Child", hp = 3, attack = 1 }
THREAT_STATS.T_FURNACE = { name = "The Furnace Woke Up", hp = 0, attack = 0 }
THREAT_STATS.T_CLOCK_STOPS = { name = "Every Clock Stopped", hp = 0, attack = 0 }
THREAT_STATS.T_ROOTS = { name = "Roots Through the Floor", hp = 0, attack = 0 }
THREAT_STATS.T_ECHO = { name = "The Echo", hp = 0, attack = 0 }
THREAT_STATS.T_MOTH_CLOUD = { name = "Moth Cloud", hp = 0, attack = 0 }
THREAT_STATS.T_THING_IN_ATTIC = { name = "The Thing in the Attic", hp = 5, attack = 1 }
THREAT_STATS.T_WATCHER = { name = "The Watcher", hp = 0, attack = 0 }
THREAT_STATS.T_SEALED_SHED = { name = "The Sealed Shed", hp = 0, attack = 0 }
THREAT_STATS.T_SEALED_LOCKER = { name = "The Sealed Locker", hp = 0, attack = 0 }
THREAT_STATS.T_SEALED_CAR = { name = "The Sealed Car", hp = 0, attack = 0 }

-- Nickname mirror, for cards matched by name instead of id tag.
THREAT_STATS_BY_NAME = {}
for _, s in pairs(THREAT_STATS) do THREAT_STATS_BY_NAME[s.name] = s end

-- Sealed-thing rewards (Design §13.5), delivered by doPry (actions.lua).
-- The Sealed Basement is a placed object, not a card — actions.lua adds
-- SEALED_REWARDS.BASEMENT after this file loads.
SEALED_REWARDS = {}

SEALED_REWARDS.T_THE_DOOR = { market = 1, line = "Behind the door: stocked shelves. A free Item from the Market deck." }
SEALED_REWARDS.T_LOCKED_ROOM = { line = "The seven deadbolts give. Recover the Item card that was sealed inside." }
SEALED_REWARDS.T_SEALED_SHED = { resources = { Wood = 3 }, line = "The shed exhales sawdust: salvage 3 Wood." }
SEALED_REWARDS.T_SEALED_LOCKER = { resources = { Battery = 2, Cloth = 1 }, line = "The locker was somebody's kit: 2 Battery and 1 Cloth." }
SEALED_REWARDS.T_SEALED_CAR = { resources = { EnergyDrink = 2, Metal = 1 }, line = "The glovebox and the trunk: 2 Energy Drinks and 1 Metal." }
