"""`gameState` has a schema, and every field must be in it.

71 fields are read or written across 41 of 46 Lua files. Lua has no field
declarations, so a misspelling — `activeChar` for `activeChars`, `cluesFound`
for `clueCount` — is not an error: it reads as nil, silently, at runtime, in
TTS, which is the most expensive place in this project to discover anything.

The rule enforced here: every `gameState.<name>` appearing anywhere in lua/ is
either declared in `migrateGameState()` (lua/global.lua) or listed in
`TRANSIENT_FIELDS` (scripts/generate_gamestate_map.py). Both halves are needed
— the declared list is the schema, and the transient list is the reviewed set
of fields for which nil is a meaningful state.

The human-readable map is docs/gamestate.md, regenerated by the same module.
"""
import os
import re

import generate_gamestate_map as gsmap  # scripts/ is on sys.path via conftest
from conftest import ROOT


def test_every_field_is_declared_or_transient():
    declared = set(gsmap.parse_declared())
    transient = set(gsmap.transient_names())
    used = set()
    for _rel, src in gsmap.lua_files():
        used |= set(gsmap.FIELD_RE.findall(src))

    unknown = sorted(used - declared - transient)
    assert not unknown, (
        "gameState field(s) in neither migrateGameState() nor TRANSIENT_FIELDS:\n  "
        + "\n  ".join(unknown)
        + "\n\nIf this is a new field, declare its default in migrateGameState() "
          "(lua/global.lua) — the one door a restored save and the Restart path "
          "both go through. If nil is genuinely a meaningful state for it, add it "
          "to TRANSIENT_FIELDS in scripts/generate_gamestate_map.py with a reason. "
          "If it is a typo, this is the failure that caught it."
    )


def test_transient_allowlist_has_no_stale_entries():
    """A field that no longer exists must leave the allowlist.

    Otherwise the list slowly becomes a place where a typo could hide: a name
    nobody uses is a name nobody would question.
    """
    transient = gsmap.transient_names()
    used = set()
    for _rel, src in gsmap.lua_files():
        used |= set(gsmap.FIELD_RE.findall(src))

    stale = sorted(set(transient) - used)
    assert not stale, (
        f"TRANSIENT_FIELDS lists gameState field(s) no longer used anywhere in lua/: "
        f"{stale} — remove them from scripts/generate_gamestate_map.py"
    )


def test_transient_fields_are_not_also_declared():
    """A field cannot be both. If it has a default, it is not transient."""
    declared = set(gsmap.parse_declared())
    both = sorted(declared & set(gsmap.transient_names()))
    assert not both, (
        f"field(s) both declared in migrateGameState() and listed as transient: {both} "
        "— pick one. A declared default means nil is not a meaningful state."
    )


def test_onsave_persists_the_whole_table():
    """docs/gamestate.md tells the reader persistence is uniform. Keep it true.

    If onSave() ever starts excluding fields, the generated 'Persistence'
    section becomes a lie and the generator needs to learn about the exclusion
    before that section can be trusted again.
    """
    assert gsmap.onsave_is_a_bare_encode(), (
        "onSave() no longer reads `return JSON.encode(gameState)`. Per-field "
        "persistence is now a real question — teach scripts/generate_gamestate_map.py "
        "to report it, then update this test."
    )


def test_map_lists_every_field_used_in_lua():
    """The generated doc must actually cover the schema it claims to."""
    path = os.path.join(ROOT, "docs", "gamestate.md")
    assert os.path.isfile(path), (
        "docs/gamestate.md missing — run scripts/generate_gamestate_map.py")
    with open(path, encoding="utf-8") as f:
        doc = f.read()

    used = set()
    for _rel, src in gsmap.lua_files():
        used |= set(gsmap.FIELD_RE.findall(src))
    missing = sorted(f for f in used if not re.search(rf"^\| `{f}` \|", doc, re.M))
    assert not missing, (
        f"docs/gamestate.md has no row for: {missing} — rerun "
        "scripts/generate_gamestate_map.py (or python scripts/check.py)"
    )
