"""
content/notebook/*.md + content/help/glossary.md → PlayerRules.md + PlayerRules.html

The player-facing rulebook, assembled from the same single-source markdown
that feeds the in-game Notebook and Help panel (generate_notebook.py) — so
the rulebook can never drift from what the game itself says.

Two outputs at the repo root:
  PlayerRules.md    — one concatenated markdown document (GitHub-readable).
  PlayerRules.html  — a self-contained styled page. Viewable two ways:
                        * in TTS: the "Player Rules" Tablet object on the
                          table loads it via the local asset server
                          (scripts/serve_art.bat → http://localhost:8080/PlayerRules.html);
                        * in any desktop browser: open the file directly or
                          hit the same URL.

Run: python scripts/generate_player_rules.py
"""

import html
import os
import re

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
MD_OUT = os.path.join(REPO_ROOT, "PlayerRules.md")
HTML_OUT = os.path.join(REPO_ROOT, "PlayerRules.html")

# (section title, source path) — reading order for a new player.
SECTIONS = [
    ("Quick Start", "content/notebook/quickstart.md"),
    ("Full Rules", "content/notebook/full_rules.md"),
    ("The Characters", "content/notebook/character_reference.md"),
    ("Glossary", "content/help/glossary.md"),
]

BANNER = ("<!-- AUTO-GENERATED by scripts/generate_player_rules.py — do not edit. "
          "Edit content/notebook/*.md + content/help/glossary.md instead. -->")

CSS = """
body { margin: 0; padding: 0 0 4em 0; background: #14110d; color: #ddd2b8;
       font-family: Georgia, 'Times New Roman', serif; font-size: 17px; line-height: 1.55; }
main { max-width: 46em; margin: 0 auto; padding: 0 1.2em; }
h1 { color: #ffd080; font-size: 1.9em; border-bottom: 2px solid #7a5c2e;
     padding-bottom: 0.2em; margin-top: 1.6em; }
h2 { color: #f0c878; font-size: 1.35em; margin-top: 1.4em; }
h3 { color: #d8b268; font-size: 1.1em; margin-top: 1.2em; }
strong { color: #f5e6c4; }
code { background: #262019; color: #a8e6c8; padding: 0.05em 0.3em;
       border-radius: 3px; font-size: 0.9em; }
ul, ol { padding-left: 1.4em; }
li { margin: 0.25em 0; }
table { border-collapse: collapse; margin: 0.8em 0; }
th, td { border: 1px solid #5a4a30; padding: 0.3em 0.7em; text-align: left; }
th { background: #262019; color: #ffd080; }
nav { background: #1e1913; border: 1px solid #7a5c2e; border-radius: 6px;
      padding: 0.7em 1em; margin: 1.4em 0; }
nav a { color: #a8e6c8; text-decoration: none; margin-right: 1.4em; }
nav a:hover { text-decoration: underline; }
header { text-align: center; padding: 2em 0 0.4em 0; }
header .title { color: #ffd080; font-size: 2.4em; font-weight: bold; letter-spacing: 0.04em; }
header .sub { color: #8a7c5e; font-style: italic; margin-top: 0.3em; }
hr.sep { border: none; border-top: 1px dashed #5a4a30; margin: 2.5em 0; }
""".strip()


def _slug(title):
    return re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")


def _inline(text):
    """Escape HTML, then apply the inline markdown the sources use."""
    s = html.escape(text, quote=False)
    s = re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", s)          # links -> their text
    s = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", s)
    s = re.sub(r"\*([^*]+)\*", r"<em>\1</em>", s)
    s = re.sub(r"`([^`]+)`", r"<code>\1</code>", s)
    return s


def md_to_html(md):
    """The subset of markdown the content files use: #/##/### headings,
    -/1. lists, | tables, bold/italic/code/links, paragraphs."""
    out = []
    lines = md.splitlines()
    i = 0
    list_tag = None          # "ul" / "ol" currently open

    def close_list():
        nonlocal list_tag
        if list_tag:
            out.append(f"</{list_tag}>")
            list_tag = None

    while i < len(lines):
        line = lines[i].rstrip()

        if not line.strip():
            close_list()
            i += 1
            continue

        m = re.match(r"^(#{1,3})\s+(.*)$", line)
        if m:
            close_list()
            level = len(m.group(1))
            # Demote: section titles are h1s injected by this script.
            out.append(f"<h{min(3, level + 1)}>{_inline(m.group(2))}</h{min(3, level + 1)}>")
            i += 1
            continue

        if line.lstrip().startswith("|"):
            close_list()
            rows = []
            while i < len(lines) and lines[i].lstrip().startswith("|"):
                cells = [c.strip() for c in lines[i].strip().strip("|").split("|")]
                if not all(re.fullmatch(r":?-{2,}:?", c) for c in cells):  # skip ruler row
                    rows.append(cells)
                i += 1
            if rows:
                out.append("<table>")
                out.append("<tr>" + "".join(f"<th>{_inline(c)}</th>" for c in rows[0]) + "</tr>")
                for r in rows[1:]:
                    out.append("<tr>" + "".join(f"<td>{_inline(c)}</td>" for c in r) + "</tr>")
                out.append("</table>")
            continue

        m = re.match(r"^\s*[-*]\s+(.*)$", line)
        if m:
            if list_tag != "ul":
                close_list()
                out.append("<ul>")
                list_tag = "ul"
            out.append(f"<li>{_inline(m.group(1))}</li>")
            i += 1
            continue

        m = re.match(r"^\s*\d+\.\s+(.*)$", line)
        if m:
            if list_tag != "ol":
                close_list()
                out.append("<ol>")
                list_tag = "ol"
            out.append(f"<li>{_inline(m.group(1))}</li>")
            i += 1
            continue

        close_list()
        # paragraph: absorb consecutive plain lines
        para = [line]
        i += 1
        while i < len(lines) and lines[i].strip() and not re.match(r"^(#|\s*[-*]\s|\s*\d+\.\s|\s*\|)", lines[i]):
            para.append(lines[i].rstrip())
            i += 1
        out.append(f"<p>{_inline(' '.join(para))}</p>")

    close_list()
    return "\n".join(out)


def main():
    sections = []
    for title, rel in SECTIONS:
        path = os.path.join(REPO_ROOT, rel.replace("/", os.sep))
        if not os.path.isfile(path):
            raise SystemExit(f"missing source: {rel}")
        with open(path, "r", encoding="utf-8") as f:
            sections.append((title, rel, f.read().strip()))

    # ---- PlayerRules.md ----------------------------------------------------
    md_parts = [
        BANNER,
        "",
        "# Starve No More — Player Rules",
        "",
        "*Survive seven nights in the neighborhood. This rulebook is assembled from "
        "the same text the in-game Notebook and Help panel show.*",
        "",
    ]
    for title, rel, body in sections:
        md_parts.append("---")
        md_parts.append("")
        md_parts.append(f"<!-- from {rel} -->")
        md_parts.append(body)
        md_parts.append("")
    with open(MD_OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(md_parts))

    # ---- PlayerRules.html --------------------------------------------------
    nav = "<nav>" + "".join(
        f'<a href="#{_slug(t)}">{html.escape(t)}</a>' for t, _r, _b in sections) + "</nav>"
    body_parts = []
    for title, rel, body in sections:
        body_parts.append('<hr class="sep"/>')
        body_parts.append(f'<h1 id="{_slug(title)}">{html.escape(title)}</h1>')
        body_parts.append(f"<!-- from {rel} -->")
        body_parts.append(md_to_html(body))

    page = f"""<!DOCTYPE html>
{BANNER}
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>Starve No More — Player Rules</title>
<style>
{CSS}
</style>
</head>
<body>
<main>
<header>
  <div class="title">STARVE NO MORE</div>
  <div class="sub">Player Rules — survive seven nights in the neighborhood</div>
</header>
{nav}
{chr(10).join(body_parts)}
</main>
</body>
</html>
"""
    with open(HTML_OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(page)

    print(f"wrote {os.path.relpath(MD_OUT, REPO_ROOT)} and {os.path.relpath(HTML_OUT, REPO_ROOT)}")
    print(f"  sections: {', '.join(t for t, _r, _b in sections)}")


if __name__ == "__main__":
    main()
