"""
Parse content/cards_threats.csv → lua/threat_types.lua

Night Sounds (design_batch3.md §1) needs to know the TYPE of the top card
of a face-down Threat deck. TTS's deck.getObjects() exposes contained
cards' nicknames but not their tags, so this table maps nickname → type,
generated straight from the CSV so it can never drift from the cards.

Output structure:
    THREAT_TYPE_BY_NAME = {
        ["Shadow Stalker"] = "Hard",
        ["A Howling Outside"] = "Soft",
        ...
    }

Run: python scripts/generate_threat_types.py
Output: lua/threat_types.lua
"""

import csv
import os

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
CSV_PATH = os.path.join(REPO_ROOT, "content", "cards_threats.csv")
LUA_PATH = os.path.join(REPO_ROOT, "lua", "threat_types.lua")


def lua_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    if not os.path.isfile(CSV_PATH):
        raise SystemExit(f"missing source: {CSV_PATH}")

    rows = []
    with open(CSV_PATH, "r", encoding="utf-8", newline="") as f:
        for row in csv.DictReader(f):
            name = (row.get("name") or "").strip()
            ttype = (row.get("type") or "").strip()
            if name and ttype:
                rows.append((row.get("id", "").strip(), name, ttype))

    L = []
    L.append("-- threat_types.lua")
    L.append("-- AUTO-GENERATED by scripts/generate_threat_types.py — do not edit by hand.")
    L.append("-- Source: content/cards_threats.csv (name + type columns)")
    L.append("--")
    L.append("-- THREAT_TYPE_BY_NAME[nickname] = \"Hard\" | \"Soft\" | \"Persistent\"")
    L.append("-- Used by the Night Sounds dusk peek (day_loop.lua): a face-down deck")
    L.append("-- only exposes nicknames, so type is looked up here.")
    L.append("")
    L.append("THREAT_TYPE_BY_NAME = {}")
    L.append("")
    for cid, name, ttype in rows:
        L.append(f"THREAT_TYPE_BY_NAME[{lua_str(name)}] = {lua_str(ttype)}  -- {cid}")
    L.append("")

    os.makedirs(os.path.dirname(LUA_PATH), exist_ok=True)
    with open(LUA_PATH, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(L))

    print(f"wrote {os.path.relpath(LUA_PATH, REPO_ROOT)}")
    print(f"  threat names mapped: {len(rows)}")


if __name__ == "__main__":
    main()
