"""
Scan lua/*.lua → SYMBOLS.md + .luacheckrc

The Lua bundle is 25+ files of globals concatenated by build_save.py.
This generator produces:

1. SYMBOLS.md — the missing table of contents: every global function and
   top-level constant, which file owns it, and its line number. One lookup
   instead of N greps, for humans and AI agents alike.

2. .luacheckrc — a luacheck config whose `globals` list is exactly the
   bundle's own symbols plus the TTS API, so `luacheck lua/` flags reads
   or writes of anything undefined (i.e. typos like `gamestate`).

Run: python scripts/generate_symbol_index.py
Output: SYMBOLS.md, .luacheckrc (repo root)
"""

import json
import os
import re

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
LUA_DIR = os.path.join(REPO_ROOT, "lua")
MD_PATH = os.path.join(REPO_ROOT, "SYMBOLS.md")
LUACHECKRC_PATH = os.path.join(REPO_ROOT, ".luacheckrc")

FUNC_RE = re.compile(r"^function\s+([A-Za-z_][\w.]*)\s*\(", re.M)
CONST_RE = re.compile(r"^([A-Za-z_]\w*)\s*=", re.M)

# Globals provided by the TTS engine / the test stub, not the bundle.
TTS_API = [
    "Vector", "Wait", "UI", "Player", "JSON", "Global", "Turns", "Notes",
    "MusicPlayer", "Lighting", "Physics", "Time", "Color",
    "broadcastToAll", "broadcastToColor", "printToAll", "printToColor", "log",
    "getAllObjects", "getObjectsWithTag", "getObjectFromGUID",
    "spawnObject", "spawnObjectJSON", "destroyObject", "startLuaCoroutine",
    "onLoad", "onSave", "TTS",
]


def load_order():
    """File order from scripts/load_order.json (the build manifest), so the
    index reads in the same order the bundle loads."""
    with open(os.path.join(REPO_ROOT, "scripts", "load_order.json"), encoding="utf-8") as f:
        files = json.load(f)["lua"]
    if not files:
        raise SystemExit("load_order.json 'lua' list is empty")
    return files


def scan(rel_path):
    """Return [(line, kind, name)] of global definitions in one lua file."""
    path = os.path.join(LUA_DIR, rel_path.replace("/", os.sep))
    out = []
    with open(path, encoding="utf-8") as f:
        for lineno, line in enumerate(f, 1):
            m = re.match(r"^function\s+([A-Za-z_][\w.]*)\s*\(", line)
            if m:
                out.append((lineno, "function", m.group(1)))
                continue
            m = re.match(r"^([A-Za-z_]\w*)\s*=", line)
            if m and m.group(1) not in ("local",):
                out.append((lineno, "table" if "{" in line else "value", m.group(1)))
    return out


def main():
    files = load_order()
    per_file = {f: scan(f) for f in files}

    # ---- SYMBOLS.md ----
    L = []
    L.append("# Symbol Index")
    L.append("")
    L.append("*AUTO-GENERATED by `scripts/generate_symbol_index.py` — do not edit by hand.*")
    L.append("*Every global function and top-level constant in the Lua bundle, in load order.*")
    L.append("")
    total = 0
    for f in files:
        syms = per_file[f]
        total += len(syms)
        L.append(f"## lua/{f} ({len(syms)} symbols)")
        L.append("")
        if not syms:
            L.append("*(no top-level globals)*")
        else:
            L.append("| line | kind | symbol |")
            L.append("|---|---|---|")
            for lineno, kind, name in syms:
                L.append(f"| {lineno} | {kind} | `{name}` |")
        L.append("")
    L.append("## Alphabetical")
    L.append("")
    L.append("| symbol | file | line |")
    L.append("|---|---|---|")
    flat = sorted((name, f, lineno)
                  for f, syms in per_file.items()
                  for lineno, _kind, name in syms)
    for name, f, lineno in flat:
        L.append(f"| `{name}` | lua/{f} | {lineno} |")
    L.append("")
    with open(MD_PATH, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(L))

    # ---- .luacheckrc ----
    bundle_globals = sorted({name.split(".")[0]
                             for syms in per_file.values()
                             for _l, _k, name in syms})
    C = []
    C.append("-- .luacheckrc — AUTO-GENERATED by scripts/generate_symbol_index.py.")
    C.append("-- Run: luacheck lua/   (flags reads/writes of undefined globals, i.e. typos)")
    C.append('std = "lua52"')
    C.append("max_line_length = false")
    C.append("unused = false")
    C.append("unused_args = false")
    C.append("redefined = false")
    C.append("-- The bundle's own globals (defined across the concatenated files):")
    C.append("globals = {")
    for g in bundle_globals:
        C.append(f'    "{g}",')
    C.append("}")
    C.append("-- The TTS engine API (read-only from the bundle's perspective):")
    C.append("read_globals = {")
    for g in TTS_API:
        C.append(f'    "{g}",')
    C.append("}")
    C.append("")
    with open(LUACHECKRC_PATH, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(C))

    print(f"wrote {os.path.relpath(MD_PATH, REPO_ROOT)} ({total} symbols, {len(files)} files)")
    print(f"wrote {os.path.relpath(LUACHECKRC_PATH, REPO_ROOT)} ({len(bundle_globals)} bundle globals)")


if __name__ == "__main__":
    main()
