"""
content/help/character_briefings.md → lua/character_briefings.lua

The Setup walkthrough's Step 3 popup text existed twice: as CHAR_BRIEFINGS in
lua/ui_setup.lua and as prose in content/help/character_briefings.md, with
nothing binding them — and they had already drifted (the markdown told James
he lives at James's House "where Energy Drinks and Batteries are plentiful";
the shipped briefing never said so). content/CLAUDE.md tells an agent that
content/ is the source of truth for in-game text, so the natural edit landed
in the markdown and never reached the game.

Now the markdown is the source and this generator is the binding. The
freshness test (tests/test_generated_freshness.py) fails if the two drift.

Run: python scripts/generate_character_briefings.py
Output: lua/character_briefings.lua
"""
import os
import re

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
SRC_PATH = os.path.join(REPO_ROOT, "content", "help", "character_briefings.md")
OUT_PATH = os.path.join(REPO_ROOT, "lua", "character_briefings.lua")

# The five playable characters. Mirrors CHARACTER_STATS/CHARACTER_COLORS in
# lua/global.lua; tests/test_cross_refs.py keeps the rosters honest.
EXPECTED = ["James", "Coco", "Rayman", "Ellie", "Luca"]

OPENER_RE = re.compile(r"^\*\*(You are .+?)\*\*$")
SECTION_RE = re.compile(r"^\*\*(Strengths|Constraints?)\*\*$")
FIELD_RE = re.compile(r"^\*\*(Starting hand|First move):\*\*\s*(.+)$")
BULLET_RE = re.compile(r"^-\s+(.+)$")


def parse(text):
    """{name: briefing_string} in the exact shape the dialog expects."""
    briefings = {}
    # Sections start at "## Name"; the file's own preamble has no ## heading
    # other than "## Format", which carries no opener line and is skipped.
    chunks = re.split(r"^##\s+(.+?)\s*$", text, flags=re.M)[1:]
    for name, body in zip(chunks[0::2], chunks[1::2]):
        parts = []
        opener = None
        flavour = []
        section = None
        bullets = []

        def flush_section(section, bullets, parts=parts):
            """Emit "Strengths:\\n- a\\n- b" for the section just finished."""
            if section and bullets:
                parts.append(f"{section}:\n" + "\n".join(f"- {b}" for b in bullets))

        for raw in body.splitlines():
            line = raw.strip()
            if not line or line == "---":
                continue
            m = OPENER_RE.match(line)
            if m:
                opener = m.group(1)
                continue
            m = SECTION_RE.match(line)
            if m:
                flush_section(section, bullets)
                section, bullets = m.group(1), []
                continue
            m = FIELD_RE.match(line)
            if m:
                flush_section(section, bullets)
                section, bullets = None, []
                parts.append(f"{m.group(1)}: {m.group(2).strip()}")
                continue
            m = BULLET_RE.match(line)
            if m and section:
                bullets.append(m.group(1).strip())
                continue
            if opener and not section and not parts:
                flavour.append(line)
        flush_section(section, bullets)

        if not opener:
            continue  # a prose section (e.g. "## Format"), not a character
        body_parts = [opener]
        if flavour:
            body_parts.append(" ".join(flavour))
        body_parts.extend(parts)
        briefings[name] = "\n\n".join(body_parts)
    return briefings


def lua_quote(s):
    """Lua double-quoted string. Only \\ and " need escaping; newlines are \\n."""
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def main():
    with open(SRC_PATH, encoding="utf-8") as f:
        briefings = parse(f.read())

    missing = [n for n in EXPECTED if n not in briefings]
    if missing:
        raise SystemExit(
            f"content/help/character_briefings.md has no briefing for: {missing}. "
            "Each character needs a '## <Name>' section whose first line is "
            "'**You are <Name>, the <Role>.**' — see the Format section in that file.")
    extra = [n for n in briefings if n not in EXPECTED]
    if extra:
        raise SystemExit(
            f"content/help/character_briefings.md has briefing section(s) for "
            f"unknown character(s): {extra}. The roster is {EXPECTED} "
            "(CHARACTER_STATS in lua/global.lua).")

    L = []
    L.append("-- character_briefings.lua")
    L.append("-- AUTO-GENERATED by scripts/generate_character_briefings.py "
             "— do not edit by hand.")
    L.append("-- Source: content/help/character_briefings.md")
    L.append("--")
    L.append("-- The Setup walkthrough's Step 3 popup (Design §18.16), shown once to each")
    L.append("-- player after they pick, and reused as the pick-card hover tooltip. Plain")
    L.append("-- text on purpose: formatBriefingBody (ui_setup.lua) adds the rich-text")
    L.append("-- styling for the dialog, and a tooltip would render the tags literally.")
    L.append("CHAR_BRIEFINGS = {")
    for name in EXPECTED:
        L.append(f"    {name} = {lua_quote(briefings[name])},")
    L.append("}")
    L.append("")

    with open(OUT_PATH, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(L))

    print(f"wrote {os.path.relpath(OUT_PATH, REPO_ROOT)} "
          f"({len(briefings)} briefings, "
          f"{sum(len(v) for v in briefings.values())} chars)")


if __name__ == "__main__":
    main()
