"""
Parse content/achievements.csv → lua/achievement_data.lua + steam/achievements.json

One source row, three consumers:

  * lua/achievement_data.lua — the in-game roster (name, description, category,
    hidden flag, icon asset name). The *unlock logic* is NOT generated: it lives
    in lua/achievement_rules.lua as one predicate per id, and
    tests/test_lua_achievements.py fails if the two lists ever disagree.
  * steam/achievements.json — the Steamworks-shaped manifest (API name, display
    name, description, hidden, icon file names), for the day this ships outside
    Tabletop Simulator. See docs/achievements.md for why a TTS mod cannot award
    real Steam achievements itself.
  * scripts/generate_achievement_icons.py reads the same CSV for its art_notes
    (the ComfyUI prompts) and its icon file names.

Run: python scripts/generate_achievement_data.py
Output: lua/achievement_data.lua, steam/achievements.json
"""

import csv
import json
import os
import re

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
CSV_PATH = os.path.join(REPO_ROOT, "content", "achievements.csv")
LUA_PATH = os.path.join(REPO_ROOT, "lua", "achievement_data.lua")
STEAM_PATH = os.path.join(REPO_ROOT, "steam", "achievements.json")

ID_RE = re.compile(r"A_[A-Z0-9_]+$")


def lua_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def icon_base(aid):
    """art/achievements/<base>.png — the id without its A_ prefix, lowercased."""
    return aid[2:].lower()


def load_rows():
    if not os.path.isfile(CSV_PATH):
        raise SystemExit(f"missing source: {CSV_PATH}")
    rows = []
    seen = set()
    with open(CSV_PATH, "r", encoding="utf-8", newline="") as f:
        for row in csv.DictReader(f):
            aid = (row.get("id") or "").strip()
            if not aid:
                continue
            if not ID_RE.match(aid):
                raise SystemExit(f"{aid}: achievement ids must match A_[A-Z0-9_]+")
            if aid in seen:
                raise SystemExit(f"{aid}: duplicate id")
            seen.add(aid)
            for col in ("api_name", "name", "description", "category"):
                if not (row.get(col) or "").strip():
                    raise SystemExit(f"{aid}: empty {col} column")
            hidden = (row.get("hidden") or "0").strip()
            if hidden not in ("0", "1"):
                raise SystemExit(f"{aid}: hidden must be 0 or 1, got {hidden!r}")
            rows.append({
                "id": aid,
                "api_name": row["api_name"].strip(),
                "name": row["name"].strip(),
                "description": row["description"].strip(),
                "hidden": hidden == "1",
                "category": row["category"].strip(),
                "condition": (row.get("condition") or "").strip(),
                "art_notes": (row.get("art_notes") or "").strip(),
            })
    if not rows:
        raise SystemExit("achievements.csv has no data rows")
    return rows


def write_lua(rows):
    L = []
    L.append("-- achievement_data.lua")
    L.append("-- AUTO-GENERATED by scripts/generate_achievement_data.py — do not edit by hand.")
    L.append("-- Source: content/achievements.csv")
    L.append("--")
    L.append("-- ACHIEVEMENTS[id] = { apiName, name, description, hidden, category, icon }")
    L.append("-- ACHIEVEMENT_ORDER  = ids in CSV order (the panel's reading order)")
    L.append("-- ACHIEVEMENT_CATEGORIES = category names in first-seen order")
    L.append("--")
    L.append("-- The UNLOCK CONDITION for each id lives in lua/achievement_rules.lua")
    L.append("-- (ACHIEVEMENT_RULES). A roster entry with no rule, or a rule with no")
    L.append("-- roster entry, fails tests/test_lua_achievements.py.")
    L.append("")
    L.append("ACHIEVEMENTS = {}")
    L.append("")
    for r in rows:
        parts = [
            f"apiName = {lua_str(r['api_name'])}",
            f"name = {lua_str(r['name'])}",
            f"description = {lua_str(r['description'])}",
            f"category = {lua_str(r['category'])}",
            f"icon = {lua_str('ach_' + icon_base(r['id']))}",
        ]
        if r["hidden"]:
            parts.append("hidden = true")
        L.append(f"ACHIEVEMENTS.{r['id']} = {{ {', '.join(parts)} }}")
    L.append("")
    L.append("ACHIEVEMENT_ORDER = {")
    for r in rows:
        L.append(f"    {lua_str(r['id'])},")
    L.append("}")
    L.append("")
    cats = []
    for r in rows:
        if r["category"] not in cats:
            cats.append(r["category"])
    L.append("ACHIEVEMENT_CATEGORIES = { " + ", ".join(lua_str(c) for c in cats) + " }")
    L.append("")

    with open(LUA_PATH, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(L))
    return cats


def write_steam(rows):
    """Steamworks 'Achievement' stat rows, in the shape the partner site's
    bulk-import expects: one object per achievement with its API name, the
    localized display strings, the hidden flag and both icon file names."""
    manifest = {
        "_comment": (
            "AUTO-GENERATED by scripts/generate_achievement_data.py from "
            "content/achievements.csv. Upload targets: Steamworks > Stats & "
            "Achievements. icon/icon_gray are the file names produced by "
            "scripts/generate_achievement_icons.py under art/achievements/steam/. "
            "A Tabletop Simulator Workshop mod cannot set these — see "
            "docs/achievements.md."
        ),
        "achievements": [
            {
                "name": r["api_name"],
                "displayName": {"english": r["name"]},
                "description": {"english": r["description"]},
                "hidden": 1 if r["hidden"] else 0,
                "icon": f"{icon_base(r['id'])}.jpg",
                "icon_gray": f"{icon_base(r['id'])}_gray.jpg",
            }
            for r in rows
        ],
    }
    os.makedirs(os.path.dirname(STEAM_PATH), exist_ok=True)
    with open(STEAM_PATH, "w", encoding="utf-8", newline="\n") as f:
        json.dump(manifest, f, indent=2, ensure_ascii=False)
        f.write("\n")


def main():
    rows = load_rows()
    cats = write_lua(rows)
    write_steam(rows)
    print(f"wrote {os.path.relpath(LUA_PATH, REPO_ROOT)}")
    print(f"wrote {os.path.relpath(STEAM_PATH, REPO_ROOT)}")
    print(f"  achievements: {len(rows)} in {len(cats)} categories "
          f"({sum(1 for r in rows if r['hidden'])} hidden)")


if __name__ == "__main__":
    main()
