"""
Generate lua/audio_manifest.lua from the on-disk sounds/ tree.

Walks `sounds/` and emits a Lua table grouping URLs + durations by category:
  - AUDIO.AMBIENT_SUBURBAN  — sounds/ambient/suburban/*
  - AUDIO.AMBIENT_VARIED    — sounds/ambient/varied/*
  - AUDIO.CREATURES.<name>  — sounds/creatures/<name>/*  (bearger/deerclops/eye_of_terror/treeguard)
  - AUDIO.SFX.tick_chime    — sounds/sfx/tick_chime.wav

Durations:
  - .wav files: read precisely via stdlib `wave` module
  - .mp3 files: estimated from file size assuming ~128 kbps (16 KB/s).
    The estimate only needs to be roughly right — we use it as a Wait.time
    after which we schedule the next track. A few seconds off-by means a
    few seconds of dead air before the next ambient track starts.

Run: python scripts/generate_audio_manifest.py
Output: lua/audio_manifest.lua
"""

import os
import wave

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
SOUNDS_DIR = os.path.join(REPO_ROOT, "sounds")
OUT_LUA = os.path.join(REPO_ROOT, "lua", "audio_manifest.lua")
URL_BASE = "http://localhost:8080"

# Estimate for VBR/CBR mp3 average bitrate (bytes/sec). 128 kbps ≈ 16000 B/s.
MP3_AVG_BPS = 16000


def wav_duration(path):
    with wave.open(path, "rb") as w:
        frames = w.getnframes()
        rate = w.getframerate()
        return frames / float(rate) if rate else 0.0


def mp3_duration_estimate(path):
    return os.path.getsize(path) / float(MP3_AVG_BPS)


def duration_for(path):
    p = path.lower()
    if p.endswith(".wav"):
        try:
            return wav_duration(path)
        except wave.Error:
            return os.path.getsize(path) / 88200.0  # fallback: 16-bit 44.1k mono
    if p.endswith(".mp3"):
        return mp3_duration_estimate(path)
    return None


def url_for(rel_path):
    # Forward slashes only; no URL encoding here — keep dev simple.
    rel = rel_path.replace("\\", "/")
    return f"{URL_BASE}/{rel}"


def list_clips(rel_dir):
    """Yield (filename, url, duration) for audio files directly under rel_dir."""
    abs_dir = os.path.join(REPO_ROOT, rel_dir)
    if not os.path.isdir(abs_dir):
        return []
    out = []
    for fname in sorted(os.listdir(abs_dir)):
        ap = os.path.join(abs_dir, fname)
        if not os.path.isfile(ap):
            continue
        if not fname.lower().endswith((".wav", ".mp3", ".ogg")):
            continue
        dur = duration_for(ap)
        if dur is None or dur <= 0:
            print(f"  warn: zero/unknown duration for {ap}; defaulting to 180")
            dur = 180.0
        rel = os.path.join(rel_dir, fname).replace("\\", "/")
        out.append((fname, url_for(rel), dur))
    return out


def lua_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def emit_table(lines, indent, items):
    """items: list of (filename, url, duration). Writes one entry per line."""
    pad = " " * indent
    for fname, url, dur in items:
        lines.append(f"{pad}{{ url = {lua_str(url)}, duration = {dur:.2f}, name = {lua_str(fname)} }},")


def main():
    suburban = list_clips("sounds/ambient/suburban")
    varied   = list_clips("sounds/ambient/varied")
    creatures = {}
    creatures_dir = os.path.join(SOUNDS_DIR, "creatures")
    if os.path.isdir(creatures_dir):
        for boss in sorted(os.listdir(creatures_dir)):
            full = os.path.join(creatures_dir, boss)
            if os.path.isdir(full):
                creatures[boss] = list_clips(f"sounds/creatures/{boss}")
    # All files under sounds/sfx/ become AUDIO.SFX.<key> entries.
    # Key = filename stem, lowercased, with a trailing "_sound" stripped.
    sfx_dir = os.path.join(SOUNDS_DIR, "sfx")
    sfx_entries = {}  # key -> (filename, url, duration)
    if os.path.isdir(sfx_dir):
        for fname in sorted(os.listdir(sfx_dir)):
            ap = os.path.join(sfx_dir, fname)
            if not os.path.isfile(ap):
                continue
            if not fname.lower().endswith((".wav", ".mp3", ".ogg")):
                continue
            stem = os.path.splitext(fname)[0]
            key = stem.lower()
            if key.endswith("_sound"):
                key = key[: -len("_sound")]
            dur = duration_for(ap) or 1.5
            sfx_entries[key] = (
                fname,
                url_for(f"sounds/sfx/{fname}"),
                dur,
            )

    L = []
    L.append("-- audio_manifest.lua")
    L.append("-- AUTO-GENERATED by scripts/generate_audio_manifest.py — do not edit by hand.")
    L.append("-- Sources: sounds/ambient/suburban, sounds/ambient/varied, sounds/creatures/*, sounds/sfx")
    L.append("-- Durations: precise for .wav; estimated from filesize for .mp3 (avg 128 kbps).")
    L.append("")
    L.append("AUDIO = {}")
    L.append("")
    L.append("AUDIO.AMBIENT_SUBURBAN = {")
    emit_table(L, 4, suburban)
    L.append("}")
    L.append("")
    L.append("AUDIO.AMBIENT_VARIED = {")
    emit_table(L, 4, varied)
    L.append("}")
    L.append("")
    L.append("AUDIO.CREATURES = {}")
    for boss in sorted(creatures.keys()):
        L.append(f"AUDIO.CREATURES.{boss} = {{")
        emit_table(L, 4, creatures[boss])
        L.append("}")
        L.append("")
    L.append("AUDIO.SFX = {}")
    for key in sorted(sfx_entries.keys()):
        fname, url, dur = sfx_entries[key]
        L.append(f"AUDIO.SFX.{key} = {{ url = {lua_str(url)}, duration = {dur:.2f}, name = {lua_str(fname)} }}")
    L.append("")

    os.makedirs(os.path.dirname(OUT_LUA), exist_ok=True)
    with open(OUT_LUA, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(L))

    # Summary
    counts = {
        "AMBIENT_SUBURBAN": len(suburban),
        "AMBIENT_VARIED":   len(varied),
    }
    for boss, items in creatures.items():
        counts[f"CREATURES.{boss}"] = len(items)
    counts["SFX (total)"] = len(sfx_entries)
    print(f"wrote {os.path.relpath(OUT_LUA, REPO_ROOT)}")
    for k, v in counts.items():
        print(f"  {k}: {v}")
    if sfx_entries:
        print("  SFX keys: " + ", ".join(sorted(sfx_entries.keys())))


if __name__ == "__main__":
    main()
