"""
Parse content/cards_threats.csv → lua/threat_types.lua

Three tables, all generated straight from the CSV so they can never drift
from the printed cards:

1. THREAT_TYPE_BY_NAME — Night Sounds (design_batch3.md §1) needs the TYPE
   of the top card of a face-down Threat deck; TTS's deck.getObjects()
   exposes nicknames but not tags, so this maps nickname → type.

2. THREAT_STATS — statlines (hp/attack) per card id, for the scripted
   Fight action (doFightTarget, actions.lua). Cards with hp 0 are not
   fightable (Soft events, The Grue, and the hp-less Persistents); they
   are emitted anyway so the Lua can tell "not fightable" from "unknown".
   THREAT_STATS_BY_NAME mirrors it by nickname for hand-placed cards.

3. SEALED_REWARDS — what doPry (actions.lua) delivers per sealed threat,
   from the `pry_reward` column (empty for non-sealed threats). Grammar,
   directives separated by `|`:
       market=1                        free draws off the Market deck
       resources=Wood:3+Battery:2      tokens spilled from the supply bags
       line=<flavor broadcast>         the story beat
   (The Sealed Basement is a placed object, not a card — actions.lua adds
   its SEALED_REWARDS.BASEMENT entry after this file loads.)

Run: python scripts/generate_threat_types.py
Output: lua/threat_types.lua
"""

import csv
import os

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
CSV_PATH = os.path.join(REPO_ROOT, "content", "cards_threats.csv")
LUA_PATH = os.path.join(REPO_ROOT, "lua", "threat_types.lua")


def lua_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


RESOURCE_KEYS = {"Wood", "Metal", "Cloth", "Provisions", "EnergyDrink", "Battery"}


def parse_pry_reward(spec, ctx):
    """'market=1|resources=Wood:3+Battery:2|line=...' → dict."""
    out = {}
    for directive in filter(None, (d.strip() for d in spec.split("|"))):
        key, _, value = directive.partition("=")
        if key == "market":
            out["market"] = int(value)
        elif key == "resources":
            res = {}
            for term in value.split("+"):
                rname, _, qty = term.partition(":")
                if rname not in RESOURCE_KEYS:
                    raise SystemExit(f"{ctx}: unknown resource {rname!r} in pry_reward")
                res[rname] = int(qty)
            out["resources"] = res
        elif key == "line":
            out["line"] = value
        else:
            raise SystemExit(f"{ctx}: unknown pry_reward directive {key!r}")
    return out


def main():
    if not os.path.isfile(CSV_PATH):
        raise SystemExit(f"missing source: {CSV_PATH}")

    rows = []
    sealed = []
    with open(CSV_PATH, "r", encoding="utf-8", newline="") as f:
        for row in csv.DictReader(f):
            name = (row.get("name") or "").strip()
            ttype = (row.get("type") or "").strip()
            cid = (row.get("id") or "").strip()
            hp = int((row.get("hp") or "0").strip() or 0)
            attack = int((row.get("attack") or "0").strip() or 0)
            if name and ttype:
                rows.append((cid, name, ttype, hp, attack))
            reward = (row.get("pry_reward") or "").strip()
            if reward:
                sealed.append((cid, parse_pry_reward(reward, cid)))

    L = []
    L.append("-- threat_types.lua")
    L.append("-- AUTO-GENERATED by scripts/generate_threat_types.py — do not edit by hand.")
    L.append("-- Source: content/cards_threats.csv (name/type + pry_reward columns)")
    L.append("--")
    L.append("-- THREAT_TYPE_BY_ID[id] = \"Hard\" | \"Soft\" | \"Persistent\"")
    L.append("-- The authority behind identifyThreatType (night.lua). Every drawn")
    L.append("-- card carries its CSV id as a tag, so this is the lookup that always")
    L.append("-- works; the nickname mirror below is for handles that only expose a")
    L.append("-- name (the face-down deck peek).")
    L.append("THREAT_TYPE_BY_ID = {}")
    L.append("")
    for cid, _name, ttype, _hp, _atk in rows:
        L.append(f"THREAT_TYPE_BY_ID.{cid} = {lua_str(ttype)}")
    L.append("")
    L.append("-- THREAT_TYPE_BY_NAME[nickname] = \"Hard\" | \"Soft\" | \"Persistent\"")
    L.append("-- Used by the Night Sounds dusk peek (day_loop.lua): a face-down deck")
    L.append("-- only exposes nicknames, so type is looked up here.")
    L.append("")
    L.append("THREAT_TYPE_BY_NAME = {}")
    L.append("")
    for cid, name, ttype, _hp, _atk in rows:
        L.append(f"THREAT_TYPE_BY_NAME[{lua_str(name)}] = {lua_str(ttype)}  -- {cid}")
    L.append("")
    L.append("-- Statlines per card id, for the scripted Fight action (doFightTarget,")
    L.append("-- actions.lua). hp 0 = not fightable (Soft events / hp-less Persistents).")
    L.append("THREAT_STATS = {}")
    L.append("")
    for cid, name, _ttype, hp, atk in rows:
        L.append(f"THREAT_STATS.{cid} = {{ name = {lua_str(name)}, hp = {hp}, attack = {atk} }}")
    L.append("")
    L.append("-- Nickname mirror, for cards matched by name instead of id tag.")
    L.append("THREAT_STATS_BY_NAME = {}")
    L.append("for _, s in pairs(THREAT_STATS) do THREAT_STATS_BY_NAME[s.name] = s end")
    L.append("")
    L.append("-- Sealed-thing rewards (Design §13.5), delivered by doPry (actions.lua).")
    L.append("-- The Sealed Basement is a placed object, not a card — actions.lua adds")
    L.append("-- SEALED_REWARDS.BASEMENT after this file loads.")
    L.append("SEALED_REWARDS = {}")
    L.append("")
    for cid, reward in sealed:
        parts = []
        if "market" in reward:
            parts.append(f"market = {reward['market']}")
        if "resources" in reward:
            res = ", ".join(f"{k} = {v}" for k, v in sorted(reward["resources"].items()))
            parts.append(f"resources = {{ {res} }}")
        if "line" in reward:
            parts.append(f"line = {lua_str(reward['line'])}")
        L.append(f"SEALED_REWARDS.{cid} = {{ {', '.join(parts)} }}")
    L.append("")

    os.makedirs(os.path.dirname(LUA_PATH), exist_ok=True)
    with open(LUA_PATH, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(L))

    print(f"wrote {os.path.relpath(LUA_PATH, REPO_ROOT)}")
    print(f"  threat names mapped: {len(rows)}")
    print(f"  statlines: {len(rows)} ({sum(1 for r in rows if r[3] > 0)} fightable)")
    print(f"  sealed rewards: {len(sealed)}")


if __name__ == "__main__":
    main()
