"""
content/notebook/*.md + content/help/glossary.md → lua/notebook_data.lua

The in-game documentation — the TTS Notebook tabs (Quick Start / Full Rules /
Characters) and the Help panel's Quick Start + Glossary tabs — used to be
hand-copied Lua strings in ui_help.lua and build_save.py. Three copies of the
same rules text is how the in-game glossary ended up two design batches stale.

Now the markdown under content/ is the single source: this generator converts
it to plain text (headings uppercased, links/emphasis stripped) and emits the
five Lua constants. build_save.py imports md_to_text() for the physical
Quick Start notecard, so every surface renders the same words.

Run: python scripts/generate_notebook.py
Output: lua/notebook_data.lua
"""

import os
import re

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
LUA_PATH = os.path.join(REPO_ROOT, "lua", "notebook_data.lua")

# (lua constant, source markdown, consumer)
SOURCES = [
    ("NOTEBOOK_QUICKSTART", "content/notebook/quickstart.md",
     "Notebook tab 'Quick Start' (populateNotebook, ui_help.lua)"),
    ("NOTEBOOK_FULL_RULES", "content/notebook/full_rules.md",
     "Notebook tab 'Full Rules'"),
    ("NOTEBOOK_CHARACTERS", "content/notebook/character_reference.md",
     "Notebook tab 'Characters'"),
    ("HELP_QUICKSTART", "content/notebook/quickstart.md",
     "Help panel 'Quick Start' tab (refreshHelpPanel, ui_help.lua)"),
    ("HELP_GLOSSARY", "content/help/glossary.md",
     "Help panel 'Glossary' tab"),
]


def md_to_text(md):
    """Markdown → plain text for TTS notebook/help/notecard surfaces.

    Headings become UPPERCASE lines, links keep their text, bold/inline-code
    markers are stripped, list dashes stay. Deliberately simple — the source
    files use only headings, lists, bold, and links.
    """
    out = []
    for line in md.splitlines():
        s = line.rstrip()
        m = re.match(r"^(#+)\s+(.*)$", s)
        if m:
            out.append(m.group(2).upper())
            continue
        s = re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", s)   # [text](url) -> text
        s = s.replace("**", "").replace("`", "")
        out.append(s)
    text = "\n".join(out)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def lua_long_string(text):
    if "]==]" in text:
        raise SystemExit("source text contains ']==]' — pick a longer bracket level")
    return "[==[\n" + text + "]==]"


def main():
    L = []
    L.append("-- notebook_data.lua")
    L.append("-- AUTO-GENERATED by scripts/generate_notebook.py — do not edit by hand.")
    L.append("-- Source: content/notebook/*.md + content/help/glossary.md — the in-game")
    L.append("-- Notebook tabs and Help panel text are these files, converted to plain")
    L.append("-- text. Edit the markdown, rerun the generator, rebuild the save.")
    L.append("")
    for const, rel, consumer in SOURCES:
        path = os.path.join(REPO_ROOT, rel.replace("/", os.sep))
        if not os.path.isfile(path):
            raise SystemExit(f"missing source: {rel}")
        with open(path, "r", encoding="utf-8") as f:
            text = md_to_text(f.read())
        L.append(f"-- {consumer}")
        L.append(f"-- from {rel}")
        L.append(f"{const} = {lua_long_string(text)}")
        L.append("")

    with open(LUA_PATH, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(L))
    print(f"wrote {os.path.relpath(LUA_PATH, REPO_ROOT)}")
    print(f"  constants: {', '.join(c for c, _r, _u in SOURCES)}")


if __name__ == "__main__":
    main()
