"""
Parse content/help/whatnow_hints.md → lua/whatnow_hints.lua

The markdown is the authoritative source of What-now hint copy. This script
flattens the document's structure into a single Lua table `WHATNOW_HINTS`
that ui_help.lua dispatches from at runtime.

Markdown structure (canonical for this project):
  ## Pre-Game            -> WHATNOW_HINTS.PreGame
  ## Dawn                -> WHATNOW_HINTS.Dawn
  ## Day (general)       -> WHATNOW_HINTS.Day
  ## Day (character-specific situations)
      ### Low stats          -> WHATNOW_HINTS.Stats
      ### James-specific     -> WHATNOW_HINTS.James
      ### Coco-specific      -> WHATNOW_HINTS.Coco
      ### Rayman-specific    -> WHATNOW_HINTS.Rayman
      ### Ellie-specific     -> WHATNOW_HINTS.Ellie
      ### Luca-specific      -> WHATNOW_HINTS.Luca
  ## Day (location-specific) -> WHATNOW_HINTS.Location
  ## Day (strategic)         -> WHATNOW_HINTS.Strategic
  ## Dusk                    -> WHATNOW_HINTS.Dusk
  ## Night                   -> WHATNOW_HINTS.Night
  ## Tick                    -> WHATNOW_HINTS.Tick
  ## Post-Game               -> WHATNOW_HINTS.PostGame

Within each group, entries look like:
  - **key:** "value"

Run: python scripts/generate_whatnow_hints.py
Output: lua/whatnow_hints.lua
"""

import os
import re

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
MD_PATH   = os.path.join(REPO_ROOT, "content", "help", "whatnow_hints.md")
LUA_PATH  = os.path.join(REPO_ROOT, "lua", "whatnow_hints.lua")

# Map ## section title (case-insensitive substring match) → group key
SECTION_MAP = [
    ("pre-game",                  "PreGame"),
    ("dawn",                      "Dawn"),
    ("day (general)",             "Day"),
    ("day (location-specific)",   "Location"),
    ("day (strategic)",           "Strategic"),
    ("dusk",                      "Dusk"),
    ("night",                     "Night"),
    ("tick",                      "Tick"),
    ("post-game",                 "PostGame"),
]

# Map ### subsection title (under "Day (character-specific situations)")
SUBSECTION_MAP = [
    ("low stats",       "Stats"),
    ("james-specific",  "James"),
    ("coco-specific",   "Coco"),
    ("rayman-specific", "Rayman"),
    ("ellie-specific",  "Ellie"),
    ("luca-specific",   "Luca"),
]

ENTRY_RE = re.compile(r'^- \*\*([^:*]+):\*\*\s*"(.*)"\s*$')


def map_section(title):
    """Return (group_key, is_char_section) given a ## title."""
    t = title.lower().strip()
    for needle, key in SECTION_MAP:
        if needle in t:
            return key, False
    if "character-specific" in t:
        return None, True  # subsections override
    # Unknown section — preserve title as-is, sanitized
    return re.sub(r'[^A-Za-z0-9_]', '_', title.strip()), False


def map_subsection(title):
    t = title.lower().strip()
    for needle, key in SUBSECTION_MAP:
        if needle in t:
            return key
    return re.sub(r'[^A-Za-z0-9_]', '_', title.strip())


def parse(path):
    groups = {}  # group_key -> { entry_key: text }
    current_group   = None
    in_char_section = False

    with open(path, "r", encoding="utf-8") as f:
        for raw in f:
            line = raw.rstrip("\n")

            m = re.match(r'^##\s+(.+?)\s*$', line)
            if m:
                key, is_char = map_section(m.group(1))
                in_char_section = is_char
                current_group = key
                if current_group and current_group not in groups:
                    groups[current_group] = {}
                continue

            m = re.match(r'^###\s+(.+?)\s*$', line)
            if m:
                if in_char_section:
                    current_group = map_subsection(m.group(1))
                    if current_group not in groups:
                        groups[current_group] = {}
                continue

            m = ENTRY_RE.match(line)
            if m and current_group:
                entry_key = m.group(1).strip()
                value     = m.group(2)
                groups[current_group][entry_key] = value

    return groups


def lua_escape(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def emit(groups):
    L = []
    L.append("-- whatnow_hints.lua")
    L.append("-- AUTO-GENERATED by scripts/generate_whatnow_hints.py — do not edit by hand.")
    L.append("-- Source: content/help/whatnow_hints.md")
    L.append("")
    L.append("WHATNOW_HINTS = {}")
    L.append("")

    # Stable ordering for diffability.
    preferred_order = [
        "PreGame", "Dawn", "Day", "Stats",
        "James", "Coco", "Rayman", "Ellie", "Luca",
        "Location", "Strategic", "Dusk", "Night", "Tick", "PostGame",
    ]
    seen = set()
    ordered = [k for k in preferred_order if k in groups]
    for k in groups.keys():
        if k not in seen and k not in ordered:
            ordered.append(k)
        seen.add(k)

    for group in ordered:
        entries = groups.get(group) or {}
        L.append(f"WHATNOW_HINTS.{group} = {{")
        for k in sorted(entries.keys()):
            L.append(f"    {k} = {lua_escape(entries[k])},")
        L.append("}")
        L.append("")

    return "\n".join(L)


def main():
    if not os.path.isfile(MD_PATH):
        raise SystemExit(f"missing source: {MD_PATH}")
    groups = parse(MD_PATH)
    lua = emit(groups)
    os.makedirs(os.path.dirname(LUA_PATH), exist_ok=True)
    with open(LUA_PATH, "w", encoding="utf-8", newline="\n") as f:
        f.write(lua)
    total = sum(len(v) for v in groups.values())
    print(f"wrote {os.path.relpath(LUA_PATH, REPO_ROOT)} — {len(groups)} groups, {total} entries")
    for g in sorted(groups.keys()):
        print(f"  {g}: {len(groups[g])}")


if __name__ == "__main__":
    main()
