"""
Parse content/cards_recipes.csv → lua/recipe_data.lua

The recipe CSV's `script` column is the authoritative, structured encoding
of what doCook (lua/crafting.lua) actually does — the free-English `effect`
column is the card face text. This generator turns `script` into the
RECIPE_DATA table so card text and code can never drift apart.

`script` grammar (directives separated by `|`):
    allAtTile=hunger:4+sanity:2     stat table applied to everyone at the tile
    cookOnly=hunger:5               stat table applied to the cook only
    cookPenalty=health:2            stat table SUBTRACTED from the cook
    oneAlly=hunger:1                bonus one chosen ally receives
    adjacentAllies=sanity:1         bonus allies at adjacent tiles receive
    actionCost=2                    action cost (default 1)
    oncePerGame                     flag
    canCookAtNight                  flag
    requiresCrockpot                flag
    special=heart|trailmix          bespoke handler key in crafting.lua

Run: python scripts/generate_recipe_data.py
Output: lua/recipe_data.lua
"""

import csv
import os
import re

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
CSV_PATH = os.path.join(REPO_ROOT, "content", "cards_recipes.csv")
LUA_PATH = os.path.join(REPO_ROOT, "lua", "recipe_data.lua")

STAT_DIRECTIVES = ("allAtTile", "cookOnly", "cookPenalty", "oneAlly", "adjacentAllies")
FLAG_DIRECTIVES = ("oncePerGame", "canCookAtNight", "requiresCrockpot")
STATS = {"hunger", "sanity", "health"}

# Canonical resource token suffixes (Resource:<Type>), matching build_save.py
# and generate_market_data.py. The `ingredients` column is auto-paid by
# doCook, so its names must resolve to these.
RESOURCE_KEYS = {"Wood", "Metal", "Cloth", "Provisions", "EnergyDrink", "Battery"}


def canon_resource(name):
    name = name.strip()
    if name.lower() in ("energy drink", "energy-drink", "energydrink"):
        return "EnergyDrink"
    return (name[0].upper() + name[1:]) if name else ""


def parse_ingredients(spec, ctx):
    """'2 Provisions + 1 Wood' -> {'Provisions': 2, 'Wood': 1}. Errors on an unknown
    resource so a typo can't silently make a recipe free."""
    out = {}
    for term in (spec or "").split("+"):
        term = term.strip()
        if not term:
            continue
        m = re.match(r"^(\d+)\s+(.+?)\s*$", term)
        if not m:
            raise SystemExit(f"{ctx}: can't parse ingredient term {term!r}")
        rname = canon_resource(m.group(2))
        if rname not in RESOURCE_KEYS:
            raise SystemExit(f"{ctx}: unknown ingredient resource {m.group(2)!r}")
        out[rname] = out.get(rname, 0) + int(m.group(1))
    return out


def lua_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def parse_stats(spec, ctx):
    out = {}
    for term in spec.split("+"):
        stat, _, amount = term.partition(":")
        stat = stat.strip()
        if stat not in STATS:
            raise SystemExit(f"{ctx}: unknown stat {stat!r}")
        out[stat] = int(amount)
    return out


def parse_script(script, ctx):
    entry = {}
    for directive in filter(None, (d.strip() for d in script.split("|"))):
        key, _, value = directive.partition("=")
        if key in STAT_DIRECTIVES:
            entry[key] = parse_stats(value, ctx)
        elif key in FLAG_DIRECTIVES:
            entry[key] = True
        elif key == "actionCost":
            entry[key] = int(value)
        elif key == "special":
            entry[key] = value
        else:
            raise SystemExit(f"{ctx}: unknown directive {key!r}")
    return entry


def main():
    if not os.path.isfile(CSV_PATH):
        raise SystemExit(f"missing source: {CSV_PATH}")

    rows = []
    with open(CSV_PATH, "r", encoding="utf-8", newline="") as f:
        for row in csv.DictReader(f):
            rid = (row.get("id") or "").strip()
            if not rid:
                continue
            script = (row.get("script") or "").strip()
            if not script:
                raise SystemExit(f"{rid}: empty script column — every recipe needs one")
            entry = parse_script(script, rid)
            ingredients = parse_ingredients(row.get("ingredients", ""), rid)
            if ingredients:
                entry["ingredients"] = ingredients
            rows.append((rid, row.get("name", "").strip(), entry))

    L = []
    L.append("-- recipe_data.lua")
    L.append("-- AUTO-GENERATED by scripts/generate_recipe_data.py — do not edit by hand.")
    L.append("-- Source: content/cards_recipes.csv (script column)")
    L.append("--")
    L.append("-- RECIPE_DATA[recipe_id] = { name, ingredients (Resource cost, auto-paid")
    L.append("--   by doCook), allAtTile/cookOnly/cookPenalty/oneAlly/adjacentAllies stat")
    L.append("--   tables, actionCost, oncePerGame, canCookAtNight, requiresCrockpot,")
    L.append("--   special }. Consumed by doCook (crafting.lua) and the COOK buttons.")
    L.append("")
    L.append("RECIPE_DATA = {}")
    L.append("")
    for rid, name, entry in rows:
        parts = [f"name = {lua_str(name)}"]
        if "ingredients" in entry:
            ing = ", ".join(f"{k} = {v}" for k, v in sorted(entry["ingredients"].items()))
            parts.append(f"ingredients = {{ {ing} }}")
        for key in STAT_DIRECTIVES:
            if key in entry:
                stats = ", ".join(f"{k} = {v}" for k, v in sorted(entry[key].items()))
                parts.append(f"{key} = {{ {stats} }}")
        if "actionCost" in entry:
            parts.append(f"actionCost = {entry['actionCost']}")
        for key in FLAG_DIRECTIVES:
            if entry.get(key):
                parts.append(f"{key} = true")
        if "special" in entry:
            parts.append(f"special = {lua_str(entry['special'])}")
        L.append(f"RECIPE_DATA.{rid} = {{ {', '.join(parts)} }}")
    L.append("")

    with open(LUA_PATH, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(L))

    print(f"wrote {os.path.relpath(LUA_PATH, REPO_ROOT)}")
    print(f"  recipes: {len(rows)}")


if __name__ == "__main__":
    main()
